#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the AppSetting
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum appsetting_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the AppSetting
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum appsetting_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

/// <summary>
/// Holds the value for the associated App Setting Definition.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("appsetting")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class AppSetting : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public AppSetting() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "appsetting";
	
	public const string EntityLogicalCollectionName = "appsettings";
	
	public const string EntitySetName = "appsettings";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appsettingid")]
	public System.Nullable<System.Guid> AppSettingId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("appsettingid");
		}
		set
		{
			this.OnPropertyChanging("AppSettingId");
			this.SetAttributeValue("appsettingid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("AppSettingId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("appsettingid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.AppSettingId = value;
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// The description of the App Setting.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
	public string Description
	{
		get
		{
			return this.GetAttributeValue<string>("description");
		}
	}
	
	/// <summary>
	/// Display name of the App Setting.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("displayname")]
	public string DisplayName
	{
		get
		{
			return this.GetAttributeValue<string>("displayname");
		}
		set
		{
			this.OnPropertyChanging("DisplayName");
			this.SetAttributeValue("displayname", value);
			this.OnPropertyChanged("DisplayName");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Unique identifier for the organization
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	public Microsoft.Xrm.Sdk.EntityReference OrganizationId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Unique identifier for AppModule associated with AppSetting.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentappmoduleid")]
	public Microsoft.Xrm.Sdk.EntityReference ParentAppModuleId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentappmoduleid");
		}
		set
		{
			this.OnPropertyChanging("ParentAppModuleId");
			this.SetAttributeValue("parentappmoduleid", value);
			this.OnPropertyChanged("ParentAppModuleId");
		}
	}
	
	/// <summary>
	/// Unique identifier for SettingDefinition associated with AppSetting.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("settingdefinitionid")]
	public Microsoft.Xrm.Sdk.EntityReference SettingDefinitionId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("settingdefinitionid");
		}
		set
		{
			this.OnPropertyChanging("SettingDefinitionId");
			this.SetAttributeValue("settingdefinitionid", value);
			this.OnPropertyChanged("SettingDefinitionId");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Status of the AppSetting
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual appsetting_statecode? statecode
	{
		get
		{
			return ((appsetting_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
	}
	
	/// <summary>
	/// Reason for the status of the AppSetting
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual appsetting_statuscode? statuscode
	{
		get
		{
			return ((appsetting_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Unique name of the App Setting.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniquename")]
	public string UniqueName
	{
		get
		{
			return this.GetAttributeValue<string>("uniquename");
		}
		set
		{
			this.OnPropertyChanging("UniqueName");
			this.SetAttributeValue("uniquename", value);
			this.OnPropertyChanged("UniqueName");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Contains the actual value of app settings.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("value")]
	public string Value
	{
		get
		{
			return this.GetAttributeValue<string>("value");
		}
		set
		{
			this.OnPropertyChanging("Value");
			this.SetAttributeValue("value", value);
			this.OnPropertyChanged("Value");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N appsetting_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appsetting_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> appsetting_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("appsetting_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("appsetting_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("appsetting_AsyncOperations", null, value);
			this.OnPropertyChanged("appsetting_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N appsetting_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appsetting_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> appsetting_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("appsetting_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("appsetting_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("appsetting_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("appsetting_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N appsetting_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appsetting_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> appsetting_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("appsetting_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("appsetting_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("appsetting_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("appsetting_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N appsetting_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appsetting_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> appsetting_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("appsetting_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("appsetting_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("appsetting_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("appsetting_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N appsetting_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appsetting_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> appsetting_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("appsetting_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("appsetting_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("appsetting_ProcessSession", null, value);
			this.OnPropertyChanged("appsetting_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N appsetting_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appsetting_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> appsetting_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("appsetting_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("appsetting_SyncErrors");
			this.SetRelatedEntities<SyncError>("appsetting_SyncErrors", null, value);
			this.OnPropertyChanged("appsetting_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N appsetting_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appsetting_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> appsetting_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("appsetting_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("appsetting_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("appsetting_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("appsetting_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:1 appmodule_appsetting_parentappmoduleid
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentappmoduleid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("appmodule_appsetting_parentappmoduleid")]
	public AppModule appmodule_appsetting_parentappmoduleid
	{
		get
		{
			return this.GetRelatedEntity<AppModule>("appmodule_appsetting_parentappmoduleid", null);
		}
		set
		{
			this.OnPropertyChanging("appmodule_appsetting_parentappmoduleid");
			this.SetRelatedEntity<AppModule>("appmodule_appsetting_parentappmoduleid", null, value);
			this.OnPropertyChanged("appmodule_appsetting_parentappmoduleid");
		}
	}
	
	/// <summary>
	/// N:1 lk_appsetting_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_appsetting_createdby")]
	public SystemUser lk_appsetting_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_appsetting_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_appsetting_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_appsetting_createdonbehalfby")]
	public SystemUser lk_appsetting_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_appsetting_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_appsetting_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_appsetting_modifiedby")]
	public SystemUser lk_appsetting_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_appsetting_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_appsetting_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_appsetting_modifiedonbehalfby")]
	public SystemUser lk_appsetting_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_appsetting_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 organization_appsetting
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_appsetting")]
	public Organization organization_appsetting
	{
		get
		{
			return this.GetRelatedEntity<Organization>("organization_appsetting", null);
		}
	}
	
	/// <summary>
	/// N:1 settingdefinition_appsetting_settingdefinitionid
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("settingdefinitionid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("settingdefinition_appsetting_settingdefinitionid")]
	public SettingDefinition settingdefinition_appsetting_settingdefinitionid
	{
		get
		{
			return this.GetRelatedEntity<SettingDefinition>("settingdefinition_appsetting_settingdefinitionid", null);
		}
		set
		{
			this.OnPropertyChanging("settingdefinition_appsetting_settingdefinitionid");
			this.SetRelatedEntity<SettingDefinition>("settingdefinition_appsetting_settingdefinitionid", null, value);
			this.OnPropertyChanged("settingdefinition_appsetting_settingdefinitionid");
		}
	}
}
#pragma warning restore CS1591
