#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum componentversion_operation
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Create = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Update = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Publish = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Restore = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	SolutionImport = 4,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("componentversion")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class componentversion : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public componentversion() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "componentversion";
	
	public const string EntityLogicalCollectionName = "componentversions";
	
	public const string EntitySetName = "componentversions";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("changesummary")]
	public string ChangeSummary
	{
		get
		{
			return this.GetAttributeValue<string>("changesummary");
		}
		set
		{
			this.OnPropertyChanging("ChangeSummary");
			this.SetAttributeValue("changesummary", value);
			this.OnPropertyChanged("ChangeSummary");
		}
	}
	
	/// <summary>
	/// Owning component.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("component")]
	public Microsoft.Xrm.Sdk.EntityReference Component
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("component");
		}
		set
		{
			this.OnPropertyChanging("Component");
			this.SetAttributeValue("component", value);
			this.OnPropertyChanged("Component");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentversionid")]
	public System.Nullable<System.Guid> componentversionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentversionid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentversionid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			base.Id = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentversionname")]
	public string componentversionname
	{
		get
		{
			return this.GetAttributeValue<string>("componentversionname");
		}
		set
		{
			this.OnPropertyChanging("componentversionname");
			this.SetAttributeValue("componentversionname", value);
			this.OnPropertyChanged("componentversionname");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("operation")]
	public virtual componentversion_operation? Operation
	{
		get
		{
			return ((componentversion_operation?)(EntityOptionSetEnum.GetEnum(this, "operation")));
		}
		set
		{
			this.OnPropertyChanging("Operation");
			this.SetAttributeValue("operation", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("Operation");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Base version that was restored.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("restoredfromversion")]
	public Microsoft.Xrm.Sdk.EntityReference RestoredFromVersion
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("restoredfromversion");
		}
		set
		{
			this.OnPropertyChanging("RestoredFromVersion");
			this.SetAttributeValue("restoredfromversion", value);
			this.OnPropertyChanged("RestoredFromVersion");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemchangesummary")]
	public string SystemChangeSummary
	{
		get
		{
			return this.GetAttributeValue<string>("systemchangesummary");
		}
		set
		{
			this.OnPropertyChanging("SystemChangeSummary");
			this.SetAttributeValue("systemchangesummary", value);
			this.OnPropertyChanged("SystemChangeSummary");
		}
	}
	
	/// <summary>
	/// 1:N restoreversions
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("restoreversions", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
	public System.Collections.Generic.IEnumerable<componentversion> Referencedrestoreversions
	{
		get
		{
			return this.GetRelatedEntities<componentversion>("restoreversions", Microsoft.Xrm.Sdk.EntityRole.Referenced);
		}
		set
		{
			this.OnPropertyChanging("Referencedrestoreversions");
			this.SetRelatedEntities<componentversion>("restoreversions", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
			this.OnPropertyChanged("Referencedrestoreversions");
		}
	}
	
	/// <summary>
	/// N:1 desktopflowbinary_componentversions
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("component")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("desktopflowbinary_componentversions")]
	public desktopflowbinary desktopflowbinary_componentversions
	{
		get
		{
			return this.GetRelatedEntity<desktopflowbinary>("desktopflowbinary_componentversions", null);
		}
		set
		{
			this.OnPropertyChanging("desktopflowbinary_componentversions");
			this.SetRelatedEntity<desktopflowbinary>("desktopflowbinary_componentversions", null, value);
			this.OnPropertyChanged("desktopflowbinary_componentversions");
		}
	}
	
	/// <summary>
	/// N:1 lk_componentversion_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_componentversion_createdby")]
	public SystemUser lk_componentversion_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_componentversion_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_componentversion_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_componentversion_modifiedby")]
	public SystemUser lk_componentversion_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_componentversion_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 restoreversions
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("restoredfromversion")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("restoreversions", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
	public componentversion Referencingrestoreversions
	{
		get
		{
			return this.GetRelatedEntity<componentversion>("restoreversions", Microsoft.Xrm.Sdk.EntityRole.Referencing);
		}
		set
		{
			this.OnPropertyChanging("Referencingrestoreversions");
			this.SetRelatedEntity<componentversion>("restoreversions", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
			this.OnPropertyChanged("Referencingrestoreversions");
		}
	}
	
	/// <summary>
	/// N:1 team_componentversion
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_componentversion")]
	public Team team_componentversion
	{
		get
		{
			return this.GetRelatedEntity<Team>("team_componentversion", null);
		}
	}
	
	/// <summary>
	/// N:1 user_componentversion
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_componentversion")]
	public SystemUser user_componentversion
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("user_componentversion", null);
		}
	}
	
	/// <summary>
	/// N:1 uxagentproject_componentversions
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("component")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("uxagentproject_componentversions")]
	public uxagentproject uxagentproject_componentversions
	{
		get
		{
			return this.GetRelatedEntity<uxagentproject>("uxagentproject_componentversions", null);
		}
		set
		{
			this.OnPropertyChanging("uxagentproject_componentversions");
			this.SetRelatedEntity<uxagentproject>("uxagentproject_componentversions", null, value);
			this.OnPropertyChanged("uxagentproject_componentversions");
		}
	}
	
	/// <summary>
	/// N:1 uxagentprojectfile_componentversions
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("component")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("uxagentprojectfile_componentversions")]
	public uxagentprojectfile uxagentprojectfile_componentversions
	{
		get
		{
			return this.GetRelatedEntity<uxagentprojectfile>("uxagentprojectfile_componentversions", null);
		}
		set
		{
			this.OnPropertyChanging("uxagentprojectfile_componentversions");
			this.SetRelatedEntity<uxagentprojectfile>("uxagentprojectfile_componentversions", null, value);
			this.OnPropertyChanged("uxagentprojectfile_componentversions");
		}
	}
	
	/// <summary>
	/// N:1 workflow_componentversions
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("component")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("workflow_componentversions")]
	public Workflow workflow_componentversions
	{
		get
		{
			return this.GetRelatedEntity<Workflow>("workflow_componentversions", null);
		}
		set
		{
			this.OnPropertyChanging("workflow_componentversions");
			this.SetRelatedEntity<Workflow>("workflow_componentversions", null, value);
			this.OnPropertyChanged("workflow_componentversions");
		}
	}
}
#pragma warning restore CS1591
