#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Cluster Mode for the Table
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum entityclusterconfig_clustermode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Partitioned = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Replicated = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Local = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inherited = 3,
}

/// <summary>
/// Status of the Entity Cluster Configuration
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum entityclusterconfig_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Entity Cluster Configuration
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum entityclusterconfig_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

/// <summary>
/// Holds Entity Cluster configuration for entities
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("entityclusterconfig")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class EntityClusterConfig : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public EntityClusterConfig() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "entityclusterconfig";
	
	public const string EntityLogicalCollectionName = "entityclusterconfigs";
	
	public const string EntitySetName = "entityclusterconfigs";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Cluster Mode for the Table
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("clustermode")]
	public virtual entityclusterconfig_clustermode? ClusterMode
	{
		get
		{
			return ((entityclusterconfig_clustermode?)(EntityOptionSetEnum.GetEnum(this, "clustermode")));
		}
		set
		{
			this.OnPropertyChanging("ClusterMode");
			this.SetAttributeValue("clustermode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("ClusterMode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Shows the date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// When creating a partitioned entity record, if a clusterpartitionid is not specified, the entity record is created in a local partition instead of failing the creation operation.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defaulttolocalpartition")]
	public System.Nullable<bool> DefaultToLocalPartition
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("defaulttolocalpartition");
		}
		set
		{
			this.OnPropertyChanging("DefaultToLocalPartition");
			this.SetAttributeValue("defaulttolocalpartition", value);
			this.OnPropertyChanged("DefaultToLocalPartition");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityclusterconfigid")]
	public System.Nullable<System.Guid> EntityClusterConfigId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("entityclusterconfigid");
		}
		set
		{
			this.OnPropertyChanging("EntityClusterConfigId");
			this.SetAttributeValue("entityclusterconfigid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("EntityClusterConfigId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityclusterconfigid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.EntityClusterConfigId = value;
		}
	}
	
	/// <summary>
	/// The metadata for Entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("extensionofrecordid")]
	public Microsoft.Xrm.Sdk.EntityReference ExtensionOfRecordId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("extensionofrecordid");
		}
		set
		{
			this.OnPropertyChanging("ExtensionOfRecordId");
			this.SetAttributeValue("extensionofrecordid", value);
			this.OnPropertyChanged("ExtensionOfRecordId");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Information that specifies whether this component can be customized.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// The name of the  settings.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string Name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
	}
	
	/// <summary>
	/// Unique identifier for the organization
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	public Microsoft.Xrm.Sdk.EntityReference OrganizationId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("shouldautoreplicate")]
	public System.Nullable<bool> ShouldAutoReplicate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("shouldautoreplicate");
		}
		set
		{
			this.OnPropertyChanging("ShouldAutoReplicate");
			this.SetAttributeValue("shouldautoreplicate", value);
			this.OnPropertyChanged("ShouldAutoReplicate");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Status of the Entity Cluster Configuration
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual entityclusterconfig_statecode? statecode
	{
		get
		{
			return ((entityclusterconfig_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Entity Cluster Configuration
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual entityclusterconfig_statuscode? statuscode
	{
		get
		{
			return ((entityclusterconfig_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N entityclusterconfig_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entityclusterconfig_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> entityclusterconfig_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("entityclusterconfig_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("entityclusterconfig_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("entityclusterconfig_AsyncOperations", null, value);
			this.OnPropertyChanged("entityclusterconfig_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N entityclusterconfig_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entityclusterconfig_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> entityclusterconfig_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("entityclusterconfig_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("entityclusterconfig_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("entityclusterconfig_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("entityclusterconfig_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N entityclusterconfig_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entityclusterconfig_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> entityclusterconfig_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("entityclusterconfig_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("entityclusterconfig_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("entityclusterconfig_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("entityclusterconfig_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N entityclusterconfig_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entityclusterconfig_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> entityclusterconfig_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("entityclusterconfig_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("entityclusterconfig_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("entityclusterconfig_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("entityclusterconfig_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N entityclusterconfig_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entityclusterconfig_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> entityclusterconfig_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("entityclusterconfig_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("entityclusterconfig_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("entityclusterconfig_ProcessSession", null, value);
			this.OnPropertyChanged("entityclusterconfig_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N entityclusterconfig_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entityclusterconfig_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> entityclusterconfig_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("entityclusterconfig_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("entityclusterconfig_SyncErrors");
			this.SetRelatedEntities<SyncError>("entityclusterconfig_SyncErrors", null, value);
			this.OnPropertyChanged("entityclusterconfig_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N entityclusterconfig_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entityclusterconfig_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> entityclusterconfig_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("entityclusterconfig_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("entityclusterconfig_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("entityclusterconfig_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("entityclusterconfig_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:1 entityclusterconfig_extensionofrecordid
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("extensionofrecordid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entityclusterconfig_extensionofrecordid")]
	public Entity_Ent entityclusterconfig_extensionofrecordid
	{
		get
		{
			return this.GetRelatedEntity<Entity_Ent>("entityclusterconfig_extensionofrecordid", null);
		}
		set
		{
			this.OnPropertyChanging("entityclusterconfig_extensionofrecordid");
			this.SetRelatedEntity<Entity_Ent>("entityclusterconfig_extensionofrecordid", null, value);
			this.OnPropertyChanged("entityclusterconfig_extensionofrecordid");
		}
	}
	
	/// <summary>
	/// N:1 lk_entityclusterconfig_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_entityclusterconfig_createdby")]
	public SystemUser lk_entityclusterconfig_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_entityclusterconfig_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_entityclusterconfig_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_entityclusterconfig_createdonbehalfby")]
	public SystemUser lk_entityclusterconfig_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_entityclusterconfig_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_entityclusterconfig_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_entityclusterconfig_modifiedby")]
	public SystemUser lk_entityclusterconfig_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_entityclusterconfig_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_entityclusterconfig_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_entityclusterconfig_modifiedonbehalfby")]
	public SystemUser lk_entityclusterconfig_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_entityclusterconfig_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 organization_entityclusterconfig
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_entityclusterconfig")]
	public Organization organization_entityclusterconfig
	{
		get
		{
			return this.GetRelatedEntity<Organization>("organization_entityclusterconfig", null);
		}
	}
}
#pragma warning restore CS1591
