#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Group of privileges used to categorize users to provide appropriate access to secured columns.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("fieldpermission")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class FieldPermission : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public FieldPermission() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "fieldpermission";
	
	public const string EntityLogicalCollectionName = "fieldpermissions";
	
	public const string EntitySetName = "fieldpermissions";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Attribute Name.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("attributelogicalname")]
	public string AttributeLogicalName
	{
		get
		{
			return this.GetAttributeValue<string>("attributelogicalname");
		}
		set
		{
			this.OnPropertyChanging("AttributeLogicalName");
			this.SetAttributeValue("attributelogicalname", value);
			this.OnPropertyChanged("AttributeLogicalName");
		}
	}
	
	/// <summary>
	/// Can this Profile create the attribute
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cancreate")]
	public virtual field_security_permission_type? CanCreate
	{
		get
		{
			return ((field_security_permission_type?)(EntityOptionSetEnum.GetEnum(this, "cancreate")));
		}
		set
		{
			this.OnPropertyChanging("CanCreate");
			this.SetAttributeValue("cancreate", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("CanCreate");
		}
	}
	
	/// <summary>
	/// Can this Profile read the attribute
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canread")]
	public virtual field_security_permission_type? CanRead
	{
		get
		{
			return ((field_security_permission_type?)(EntityOptionSetEnum.GetEnum(this, "canread")));
		}
		set
		{
			this.OnPropertyChanging("CanRead");
			this.SetAttributeValue("canread", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("CanRead");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canreadunmasked")]
	public virtual field_security_permission_readunmasked? CanReadUnMasked
	{
		get
		{
			return ((field_security_permission_readunmasked?)(EntityOptionSetEnum.GetEnum(this, "canreadunmasked")));
		}
		set
		{
			this.OnPropertyChanging("CanReadUnMasked");
			this.SetAttributeValue("canreadunmasked", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("CanReadUnMasked");
		}
	}
	
	/// <summary>
	/// Can this Profile update the attribute
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("canupdate")]
	public virtual field_security_permission_type? CanUpdate
	{
		get
		{
			return ((field_security_permission_type?)(EntityOptionSetEnum.GetEnum(this, "canupdate")));
		}
		set
		{
			this.OnPropertyChanging("CanUpdate");
			this.SetAttributeValue("canupdate", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("CanUpdate");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	/// <summary>
	/// Entity name.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityname")]
	public string EntityName
	{
		get
		{
			return this.GetAttributeValue<string>("entityname");
		}
		set
		{
			this.OnPropertyChanging("EntityName");
			this.SetAttributeValue("entityname", value);
			this.OnPropertyChanged("EntityName");
		}
	}
	
	/// <summary>
	/// Unique identifier of the Field Permission.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fieldpermissionid")]
	public System.Nullable<System.Guid> FieldPermissionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("fieldpermissionid");
		}
		set
		{
			this.OnPropertyChanging("FieldPermissionId");
			this.SetAttributeValue("fieldpermissionid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("FieldPermissionId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fieldpermissionid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.FieldPermissionId = value;
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fieldpermissionidunique")]
	public System.Nullable<System.Guid> FieldPermissionIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("fieldpermissionidunique");
		}
	}
	
	/// <summary>
	/// Unique identifier of profile to which this privilege belongs.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fieldsecurityprofileid")]
	public Microsoft.Xrm.Sdk.EntityReference FieldSecurityProfileId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("fieldsecurityprofileid");
		}
		set
		{
			this.OnPropertyChanging("FieldSecurityProfileId");
			this.SetAttributeValue("fieldsecurityprofileid", value);
			this.OnPropertyChanged("FieldSecurityProfileId");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// Unique identifier for the organization
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	public Microsoft.Xrm.Sdk.EntityReference OrganizationId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N FieldPermission_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("FieldPermission_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> FieldPermission_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("FieldPermission_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("FieldPermission_SyncErrors");
			this.SetRelatedEntities<SyncError>("FieldPermission_SyncErrors", null, value);
			this.OnPropertyChanged("FieldPermission_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N userentityinstancedata_fieldpermission
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("userentityinstancedata_fieldpermission")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> userentityinstancedata_fieldpermission
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("userentityinstancedata_fieldpermission", null);
		}
		set
		{
			this.OnPropertyChanging("userentityinstancedata_fieldpermission");
			this.SetRelatedEntities<UserEntityInstanceData>("userentityinstancedata_fieldpermission", null, value);
			this.OnPropertyChanged("userentityinstancedata_fieldpermission");
		}
	}
	
	/// <summary>
	/// N:1 lk_fieldpermission_fieldsecurityprofileid
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fieldsecurityprofileid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_fieldpermission_fieldsecurityprofileid")]
	public FieldSecurityProfile lk_fieldpermission_fieldsecurityprofileid
	{
		get
		{
			return this.GetRelatedEntity<FieldSecurityProfile>("lk_fieldpermission_fieldsecurityprofileid", null);
		}
		set
		{
			this.OnPropertyChanging("lk_fieldpermission_fieldsecurityprofileid");
			this.SetRelatedEntity<FieldSecurityProfile>("lk_fieldpermission_fieldsecurityprofileid", null, value);
			this.OnPropertyChanged("lk_fieldpermission_fieldsecurityprofileid");
		}
	}
	
	/// <summary>
	/// N:1 solution_fieldpermission
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solution_fieldpermission")]
	public Solution solution_fieldpermission
	{
		get
		{
			return this.GetRelatedEntity<Solution>("solution_fieldpermission", null);
		}
	}
}
#pragma warning restore CS1591
