#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum fxexpression_category
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Workflow = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	BusinessRule = 1,
}

/// <summary>
/// Status of the FxExpression
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum fxexpression_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the FxExpression
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum fxexpression_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("fxexpression")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class fxexpression : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public fxexpression() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "fxexpression";
	
	public const string EntityLogicalCollectionName = "fxexpressions";
	
	public const string EntitySetName = "fxexpressions";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("category")]
	public virtual fxexpression_category? Category
	{
		get
		{
			return ((fxexpression_category?)(EntityOptionSetEnum.GetEnum(this, "category")));
		}
		set
		{
			this.OnPropertyChanging("Category");
			this.SetAttributeValue("category", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("Category");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("compiledexpression")]
	public string CompiledExpression
	{
		get
		{
			return this.GetAttributeValue<string>("compiledexpression");
		}
		set
		{
			this.OnPropertyChanging("CompiledExpression");
			this.SetAttributeValue("compiledexpression", value);
			this.OnPropertyChanged("CompiledExpression");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("context")]
	public string Context
	{
		get
		{
			return this.GetAttributeValue<string>("context");
		}
		set
		{
			this.OnPropertyChanging("Context");
			this.SetAttributeValue("context", value);
			this.OnPropertyChanged("Context");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// The dependencies for powerfx expressions
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencies")]
	public string Dependencies
	{
		get
		{
			return this.GetAttributeValue<string>("dependencies");
		}
		set
		{
			this.OnPropertyChanging("Dependencies");
			this.SetAttributeValue("dependencies", value);
			this.OnPropertyChanged("Dependencies");
		}
	}
	
	/// <summary>
	/// The name of the primary entity on which expression is defined.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitylogicalname")]
	public string EntityLogicalName1
	{
		get
		{
			return this.GetAttributeValue<string>("entitylogicalname");
		}
		set
		{
			this.OnPropertyChanging("EntityLogicalName1");
			this.SetAttributeValue("entitylogicalname", value);
			this.OnPropertyChanged("EntityLogicalName1");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("expression")]
	public string Expression
	{
		get
		{
			return this.GetAttributeValue<string>("expression");
		}
		set
		{
			this.OnPropertyChanging("Expression");
			this.SetAttributeValue("expression", value);
			this.OnPropertyChanged("Expression");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fxexpressionid")]
	public System.Nullable<System.Guid> fxexpressionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("fxexpressionid");
		}
		set
		{
			this.OnPropertyChanging("fxexpressionId");
			this.SetAttributeValue("fxexpressionid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("fxexpressionId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fxexpressionid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.fxexpressionId = value;
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// The sdkMessage on which will trigger expression execution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("messagename")]
	public string MessageName
	{
		get
		{
			return this.GetAttributeValue<string>("messagename");
		}
		set
		{
			this.OnPropertyChanging("MessageName");
			this.SetAttributeValue("messagename", value);
			this.OnPropertyChanged("MessageName");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// The name of the custom entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
		set
		{
			this.OnPropertyChanging("name");
			this.SetAttributeValue("name", value);
			this.OnPropertyChanged("name");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parameters")]
	public string Parameters
	{
		get
		{
			return this.GetAttributeValue<string>("parameters");
		}
		set
		{
			this.OnPropertyChanging("Parameters");
			this.SetAttributeValue("parameters", value);
			this.OnPropertyChanged("Parameters");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Status of the FxExpression
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual fxexpression_statecode? statecode
	{
		get
		{
			return ((fxexpression_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the FxExpression
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual fxexpression_statuscode? statuscode
	{
		get
		{
			return ((fxexpression_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Unique Name for the entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("uniquename")]
	public string UniqueName
	{
		get
		{
			return this.GetAttributeValue<string>("uniquename");
		}
		set
		{
			this.OnPropertyChanging("UniqueName");
			this.SetAttributeValue("uniquename", value);
			this.OnPropertyChanged("UniqueName");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> fxexpression_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("fxexpression_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("fxexpression_AsyncOperations", null, value);
			this.OnPropertyChanged("fxexpression_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> fxexpression_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("fxexpression_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("fxexpression_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("fxexpression_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_customapi
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_customapi")]
	public System.Collections.Generic.IEnumerable<CustomAPI> fxexpression_customapi
	{
		get
		{
			return this.GetRelatedEntities<CustomAPI>("fxexpression_customapi", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_customapi");
			this.SetRelatedEntities<CustomAPI>("fxexpression_customapi", null, value);
			this.OnPropertyChanged("fxexpression_customapi");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_DuplicateBaseRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_DuplicateBaseRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> fxexpression_DuplicateBaseRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("fxexpression_DuplicateBaseRecord", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_DuplicateBaseRecord");
			this.SetRelatedEntities<DuplicateRecord>("fxexpression_DuplicateBaseRecord", null, value);
			this.OnPropertyChanged("fxexpression_DuplicateBaseRecord");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_DuplicateMatchingRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_DuplicateMatchingRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> fxexpression_DuplicateMatchingRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("fxexpression_DuplicateMatchingRecord", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_DuplicateMatchingRecord");
			this.SetRelatedEntities<DuplicateRecord>("fxexpression_DuplicateMatchingRecord", null, value);
			this.OnPropertyChanged("fxexpression_DuplicateMatchingRecord");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> fxexpression_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("fxexpression_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("fxexpression_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("fxexpression_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> fxexpression_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("fxexpression_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("fxexpression_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("fxexpression_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> fxexpression_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("fxexpression_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("fxexpression_ProcessSession", null, value);
			this.OnPropertyChanged("fxexpression_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_sdkmessageprocessingstep
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_sdkmessageprocessingstep")]
	public System.Collections.Generic.IEnumerable<SdkMessageProcessingStep> fxexpression_sdkmessageprocessingstep
	{
		get
		{
			return this.GetRelatedEntities<SdkMessageProcessingStep>("fxexpression_sdkmessageprocessingstep", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_sdkmessageprocessingstep");
			this.SetRelatedEntities<SdkMessageProcessingStep>("fxexpression_sdkmessageprocessingstep", null, value);
			this.OnPropertyChanged("fxexpression_sdkmessageprocessingstep");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> fxexpression_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("fxexpression_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_SyncErrors");
			this.SetRelatedEntities<SyncError>("fxexpression_SyncErrors", null, value);
			this.OnPropertyChanged("fxexpression_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N fxexpression_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("fxexpression_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> fxexpression_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("fxexpression_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("fxexpression_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("fxexpression_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("fxexpression_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:1 business_unit_fxexpression
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_fxexpression")]
	public BusinessUnit business_unit_fxexpression
	{
		get
		{
			return this.GetRelatedEntity<BusinessUnit>("business_unit_fxexpression", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_fxexpression_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_fxexpression_createdby")]
	public SystemUser lk_fxexpression_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_fxexpression_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_fxexpression_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_fxexpression_createdonbehalfby")]
	public SystemUser lk_fxexpression_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_fxexpression_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_fxexpression_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_fxexpression_modifiedby")]
	public SystemUser lk_fxexpression_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_fxexpression_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_fxexpression_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_fxexpression_modifiedonbehalfby")]
	public SystemUser lk_fxexpression_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_fxexpression_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 owner_fxexpression
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_fxexpression")]
	public Owner owner_fxexpression
	{
		get
		{
			return this.GetRelatedEntity<Owner>("owner_fxexpression", null);
		}
		set
		{
			this.OnPropertyChanging("owner_fxexpression");
			this.SetRelatedEntity<Owner>("owner_fxexpression", null, value);
			this.OnPropertyChanged("owner_fxexpression");
		}
	}
	
	/// <summary>
	/// N:1 team_fxexpression
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_fxexpression")]
	public Team team_fxexpression
	{
		get
		{
			return this.GetRelatedEntity<Team>("team_fxexpression", null);
		}
	}
	
	/// <summary>
	/// N:1 user_fxexpression
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_fxexpression")]
	public SystemUser user_fxexpression
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("user_fxexpression", null);
		}
	}
}
#pragma warning restore CS1591
