#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Drop-down list for selecting the provisioning stage of the language provisioning state checkpoint.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum languageprovisioningstates_provisioningstage
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	FileBased = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	MetadataHelperDependent = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	SystemOnly = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Other = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Ribbon = 5,
}

/// <summary>
/// Container for language provisioning checkpoint states
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("languageprovisioningstate")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class LanguageProvisioningState : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public LanguageProvisioningState() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "languageprovisioningstate";
	
	public const string EntityLogicalCollectionName = "languageprovisioningstates";
	
	public const string EntitySetName = "languageprovisioningstates";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Application Version
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("applicationversion")]
	public string ApplicationVersion
	{
		get
		{
			return this.GetAttributeValue<string>("applicationversion");
		}
		set
		{
			this.OnPropertyChanging("ApplicationVersion");
			this.SetAttributeValue("applicationversion", value);
			this.OnPropertyChanged("ApplicationVersion");
		}
	}
	
	/// <summary>
	/// Language Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("languageid")]
	public System.Nullable<int> LanguageId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("languageid");
		}
		set
		{
			this.OnPropertyChanging("LanguageId");
			this.SetAttributeValue("languageid", value);
			this.OnPropertyChanged("LanguageId");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("languageprovisioningstateid")]
	public System.Nullable<System.Guid> LanguageProvisioningStateId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("languageprovisioningstateid");
		}
		set
		{
			this.OnPropertyChanging("LanguageProvisioningStateId");
			this.SetAttributeValue("languageprovisioningstateid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("LanguageProvisioningStateId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("languageprovisioningstateid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.LanguageProvisioningStateId = value;
		}
	}
	
	/// <summary>
	/// Provisioning Stage
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("provisioningstage")]
	public virtual languageprovisioningstates_provisioningstage? ProvisioningStage
	{
		get
		{
			return ((languageprovisioningstates_provisioningstage?)(EntityOptionSetEnum.GetEnum(this, "provisioningstage")));
		}
		set
		{
			this.OnPropertyChanging("ProvisioningStage");
			this.SetAttributeValue("provisioningstage", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("ProvisioningStage");
		}
	}
	
	/// <summary>
	/// Solution File Version
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionfileversion")]
	public string SolutionFileVersion
	{
		get
		{
			return this.GetAttributeValue<string>("solutionfileversion");
		}
		set
		{
			this.OnPropertyChanging("SolutionFileVersion");
			this.SetAttributeValue("solutionfileversion", value);
			this.OnPropertyChanged("SolutionFileVersion");
		}
	}
	
	/// <summary>
	/// Solution Unique Name
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionuniquename")]
	public string SolutionUniqueName
	{
		get
		{
			return this.GetAttributeValue<string>("solutionuniquename");
		}
		set
		{
			this.OnPropertyChanging("SolutionUniqueName");
			this.SetAttributeValue("solutionuniquename", value);
			this.OnPropertyChanged("SolutionUniqueName");
		}
	}
}
#pragma warning restore CS1591
