#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum mailboxstatistics_operationtype
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	IncomingEmail = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	OutgoingEmail = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	ACT = 2,
}

/// <summary>
/// Stores data regarding Mailbox processing cycles
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("mailboxstatistics")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class MailboxStatistics : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public MailboxStatistics() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "mailboxstatistics";
	
	public const string EntityLogicalCollectionName = "mailboxstatistics";
	
	public const string EntitySetName = "mailboxstatistics";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("asynceventid")]
	public System.Nullable<System.Guid> AsyncEventId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("asynceventid");
		}
	}
	
	/// <summary>
	/// Items remaining in CRM to process after this synchronization cycle.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("crmitemsbacklog")]
	public System.Nullable<int> CrmItemsBacklog
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("crmitemsbacklog");
		}
	}
	
	/// <summary>
	/// Time each exchange sync step is taking
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("individualstepdurations")]
	public string IndividualStepDurations
	{
		get
		{
			return this.GetAttributeValue<string>("individualstepdurations");
		}
	}
	
	/// <summary>
	/// Number of items processed unsuccessfully.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("itemsfailed")]
	public System.Nullable<int> ItemsFailed
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("itemsfailed");
		}
	}
	
	/// <summary>
	/// Number of items processed.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("itemsprocessed")]
	public System.Nullable<int> ItemsProcessed
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("itemsprocessed");
		}
	}
	
	/// <summary>
	/// Name of Machine on which mailbox was processed
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("machinename")]
	public string MachineName
	{
		get
		{
			return this.GetAttributeValue<string>("machinename");
		}
	}
	
	/// <summary>
	/// Regarding Mailbox.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mailboxid")]
	public Microsoft.Xrm.Sdk.EntityReference MailboxId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("mailboxid");
		}
	}
	
	/// <summary>
	/// Completion time of the synchronization cycle.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mailboxprocesscompletedon")]
	public System.Nullable<System.DateTime> MailboxProcessCompletedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mailboxprocesscompletedon");
		}
	}
	
	/// <summary>
	/// Scheduled time of the synchronization cycle.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mailboxprocessscheduledon")]
	public System.Nullable<System.DateTime> MailboxProcessScheduledOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mailboxprocessscheduledon");
		}
	}
	
	/// <summary>
	/// Start time of the synchronization cycle.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mailboxprocessstartedon")]
	public System.Nullable<System.DateTime> MailboxProcessStartedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("mailboxprocessstartedon");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mailboxstatisticsid")]
	public System.Nullable<System.Guid> MailboxStatisticsId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("mailboxstatisticsid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mailboxstatisticsid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			base.Id = value;
		}
	}
	
	/// <summary>
	/// Type of the mailbox operation
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("operationtypeid")]
	public virtual mailboxstatistics_operationtype? OperationTypeId
	{
		get
		{
			return ((mailboxstatistics_operationtype?)(EntityOptionSetEnum.GetEnum(this, "operationtypeid")));
		}
	}
	
	/// <summary>
	/// Unique identifier of the organization associated with the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	public Microsoft.Xrm.Sdk.EntityReference OrganizationId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
		}
	}
	
	/// <summary>
	/// Result of Mailbox processing cycle
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processresult")]
	public System.Nullable<bool> ProcessResult
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("processresult");
		}
	}
	
	/// <summary>
	/// Time it took to process the mailbox.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processtimeintervalinminutes")]
	public System.Nullable<int> ProcessTimeIntervalInMinutes
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("processtimeintervalinminutes");
		}
	}
	
	/// <summary>
	/// Time it took from the scheduled time to the actual start time to process the mailbox.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("scheduledtimeintervalinminutes")]
	public System.Nullable<int> ScheduledTimeIntervalInMinutes
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("scheduledtimeintervalinminutes");
		}
	}
	
	/// <summary>
	/// N:1 mailbox_mailboxstatistics
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("mailboxid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("mailbox_mailboxstatistics")]
	public Mailbox mailbox_mailboxstatistics
	{
		get
		{
			return this.GetRelatedEntity<Mailbox>("mailbox_mailboxstatistics", null);
		}
	}
	
	/// <summary>
	/// N:1 organization_mailboxstatistics
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_mailboxstatistics")]
	public Organization organization_mailboxstatistics
	{
		get
		{
			return this.GetRelatedEntity<Organization>("organization_mailboxstatistics", null);
		}
	}
}
#pragma warning restore CS1591
