#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Dataflow DatalakeFolder
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_dataflow_datalakefolder_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Dataflow DatalakeFolder
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_dataflow_datalakefolder_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_dataflow_datalakefolder")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class msdyn_dataflow_datalakefolder : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public msdyn_dataflow_datalakefolder() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "msdyn_dataflow_datalakefolder";
	
	public const string EntityLogicalCollectionName = "msdyn_dataflow_datalakefolders";
	
	public const string EntitySetName = "msdyn_dataflow_datalakefolders";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dataflowid")]
	public string dataflowid
	{
		get
		{
			return this.GetAttributeValue<string>("dataflowid");
		}
		set
		{
			this.OnPropertyChanging("dataflowid");
			this.SetAttributeValue("dataflowid", value);
			this.OnPropertyChanged("dataflowid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datalakefolderid")]
	public string datalakefolderid
	{
		get
		{
			return this.GetAttributeValue<string>("datalakefolderid");
		}
		set
		{
			this.OnPropertyChanging("datalakefolderid");
			this.SetAttributeValue("datalakefolderid", value);
			this.OnPropertyChanged("datalakefolderid");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_dataflow_datalakefolder")]
	public string msdyn_dataflow_datalakefolder1
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_dataflow_datalakefolder");
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder1");
			this.SetAttributeValue("msdyn_dataflow_datalakefolder", value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder1");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_dataflow_datalakefolderid")]
	public System.Nullable<System.Guid> msdyn_dataflow_datalakefolderId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_dataflow_datalakefolderid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolderId");
			this.SetAttributeValue("msdyn_dataflow_datalakefolderid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("msdyn_dataflow_datalakefolderId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_dataflow_datalakefolderid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.msdyn_dataflow_datalakefolderId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_datalakefolder")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_DatalakeFolder
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_datalakefolder");
		}
		set
		{
			this.OnPropertyChanging("msdyn_DatalakeFolder");
			this.SetAttributeValue("msdyn_datalakefolder", value);
			this.OnPropertyChanged("msdyn_DatalakeFolder");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("originaldataflowid")]
	public string originaldataflowid
	{
		get
		{
			return this.GetAttributeValue<string>("originaldataflowid");
		}
		set
		{
			this.OnPropertyChanging("originaldataflowid");
			this.SetAttributeValue("originaldataflowid", value);
			this.OnPropertyChanged("originaldataflowid");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Status of the Dataflow DatalakeFolder
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual msdyn_dataflow_datalakefolder_statecode? statecode
	{
		get
		{
			return ((msdyn_dataflow_datalakefolder_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Dataflow DatalakeFolder
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual msdyn_dataflow_datalakefolder_statuscode? statuscode
	{
		get
		{
			return ((msdyn_dataflow_datalakefolder_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dataflow_datalakefolder_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> msdyn_dataflow_datalakefolder_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("msdyn_dataflow_datalakefolder_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("msdyn_dataflow_datalakefolder_AsyncOperations", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dataflow_datalakefolder_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> msdyn_dataflow_datalakefolder_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("msdyn_dataflow_datalakefolder_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("msdyn_dataflow_datalakefolder_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dataflow_datalakefolder_DuplicateBaseRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_DuplicateBaseRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> msdyn_dataflow_datalakefolder_DuplicateBaseRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("msdyn_dataflow_datalakefolder_DuplicateBaseRecord", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_DuplicateBaseRecord");
			this.SetRelatedEntities<DuplicateRecord>("msdyn_dataflow_datalakefolder_DuplicateBaseRecord", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_DuplicateBaseRecord");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dataflow_datalakefolder_DuplicateMatchingRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_DuplicateMatchingRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> msdyn_dataflow_datalakefolder_DuplicateMatchingRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("msdyn_dataflow_datalakefolder_DuplicateMatchingRecord", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_DuplicateMatchingRecord");
			this.SetRelatedEntities<DuplicateRecord>("msdyn_dataflow_datalakefolder_DuplicateMatchingRecord", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_DuplicateMatchingRecord");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dataflow_datalakefolder_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> msdyn_dataflow_datalakefolder_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("msdyn_dataflow_datalakefolder_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("msdyn_dataflow_datalakefolder_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dataflow_datalakefolder_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> msdyn_dataflow_datalakefolder_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("msdyn_dataflow_datalakefolder_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("msdyn_dataflow_datalakefolder_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dataflow_datalakefolder_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> msdyn_dataflow_datalakefolder_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("msdyn_dataflow_datalakefolder_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("msdyn_dataflow_datalakefolder_ProcessSession", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dataflow_datalakefolder_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> msdyn_dataflow_datalakefolder_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("msdyn_dataflow_datalakefolder_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_SyncErrors");
			this.SetRelatedEntities<SyncError>("msdyn_dataflow_datalakefolder_SyncErrors", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dataflow_datalakefolder_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> msdyn_dataflow_datalakefolder_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("msdyn_dataflow_datalakefolder_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("msdyn_dataflow_datalakefolder_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:1 business_unit_msdyn_dataflow_datalakefolder
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_msdyn_dataflow_datalakefolder")]
	public BusinessUnit business_unit_msdyn_dataflow_datalakefolder
	{
		get
		{
			return this.GetRelatedEntity<BusinessUnit>("business_unit_msdyn_dataflow_datalakefolder", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_dataflow_datalakefolder_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_dataflow_datalakefolder_createdby")]
	public SystemUser lk_msdyn_dataflow_datalakefolder_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_dataflow_datalakefolder_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_dataflow_datalakefolder_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_dataflow_datalakefolder_createdonbehalfby")]
	public SystemUser lk_msdyn_dataflow_datalakefolder_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_dataflow_datalakefolder_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_dataflow_datalakefolder_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_dataflow_datalakefolder_modifiedby")]
	public SystemUser lk_msdyn_dataflow_datalakefolder_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_dataflow_datalakefolder_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_dataflow_datalakefolder_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_dataflow_datalakefolder_modifiedonbehalfby")]
	public SystemUser lk_msdyn_dataflow_datalakefolder_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_dataflow_datalakefolder_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 msdyn_dataflow_datalakefolder_dataflow
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_dataflow")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_dataflow")]
	public msdyn_dataflow msdyn_dataflow_datalakefolder_dataflow
	{
		get
		{
			return this.GetRelatedEntity<msdyn_dataflow>("msdyn_dataflow_datalakefolder_dataflow", null);
		}
	}
	
	/// <summary>
	/// N:1 msdyn_dataflow_datalakefolder_dlfolder
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_datalakefolder")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dataflow_datalakefolder_dlfolder")]
	public datalakefolder msdyn_dataflow_datalakefolder_dlfolder
	{
		get
		{
			return this.GetRelatedEntity<datalakefolder>("msdyn_dataflow_datalakefolder_dlfolder", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dataflow_datalakefolder_dlfolder");
			this.SetRelatedEntity<datalakefolder>("msdyn_dataflow_datalakefolder_dlfolder", null, value);
			this.OnPropertyChanged("msdyn_dataflow_datalakefolder_dlfolder");
		}
	}
	
	/// <summary>
	/// N:1 owner_msdyn_dataflow_datalakefolder
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_msdyn_dataflow_datalakefolder")]
	public Owner owner_msdyn_dataflow_datalakefolder
	{
		get
		{
			return this.GetRelatedEntity<Owner>("owner_msdyn_dataflow_datalakefolder", null);
		}
		set
		{
			this.OnPropertyChanging("owner_msdyn_dataflow_datalakefolder");
			this.SetRelatedEntity<Owner>("owner_msdyn_dataflow_datalakefolder", null, value);
			this.OnPropertyChanged("owner_msdyn_dataflow_datalakefolder");
		}
	}
	
	/// <summary>
	/// N:1 team_msdyn_dataflow_datalakefolder
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_msdyn_dataflow_datalakefolder")]
	public Team team_msdyn_dataflow_datalakefolder
	{
		get
		{
			return this.GetRelatedEntity<Team>("team_msdyn_dataflow_datalakefolder", null);
		}
	}
	
	/// <summary>
	/// N:1 user_msdyn_dataflow_datalakefolder
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_msdyn_dataflow_datalakefolder")]
	public SystemUser user_msdyn_dataflow_datalakefolder
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("user_msdyn_dataflow_datalakefolder", null);
		}
	}
}
#pragma warning restore CS1591
