#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_flow_awaitallactionapprovalmodel_user")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class msdyn_flow_awaitallactionapprovalmodel_user : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public msdyn_flow_awaitallactionapprovalmodel_user() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "msdyn_flow_awaitallactionapprovalmodel_user";
	
	public const string EntityLogicalCollectionName = null;
	
	public const string EntitySetName = "msdyn_flow_awaitallactionapprovalmodel_userset";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_awaitallactionapprovalmodel_userid")]
	public System.Nullable<System.Guid> msdyn_flow_awaitallactionapprovalmodel_userId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_flow_awaitallactionapprovalmodel_userid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_awaitallactionapprovalmodel_userid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			base.Id = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_awaitallactionapprovalmodelid")]
	public System.Nullable<System.Guid> msdyn_flow_awaitallactionapprovalmodelid
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_flow_awaitallactionapprovalmodelid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("systemuserid")]
	public System.Nullable<System.Guid> systemuserid
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("systemuserid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:N msdyn_flow_awaitallactionmodelrelationship_user
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_awaitallactionmodelrelationship_user")]
	public System.Collections.Generic.IEnumerable<msdyn_flow_awaitallactionapprovalmodel> msdyn_flow_awaitallactionmodelrelationship_user
	{
		get
		{
			return this.GetRelatedEntities<msdyn_flow_awaitallactionapprovalmodel>("msdyn_flow_awaitallactionmodelrelationship_user", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_awaitallactionmodelrelationship_user");
			this.SetRelatedEntities<msdyn_flow_awaitallactionapprovalmodel>("msdyn_flow_awaitallactionmodelrelationship_user", null, value);
			this.OnPropertyChanged("msdyn_flow_awaitallactionmodelrelationship_user");
		}
	}
}
#pragma warning restore CS1591
