#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Approval Step
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_flow_approvalstep_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Approval Step
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_flow_approvalstep_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_flow_approvalstep")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class msdyn_flow_approvalstep : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public msdyn_flow_approvalstep() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "msdyn_flow_approvalstep";
	
	public const string EntityLogicalCollectionName = "msdyn_flow_approvalsteps";
	
	public const string EntitySetName = "msdyn_flow_approvalsteps";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_approval")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_flow_approvalstep_approval
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_flow_approvalstep_approval");
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_approval");
			this.SetAttributeValue("msdyn_flow_approvalstep_approval", value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_approval");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_approvalid")]
	public string msdyn_flow_approvalstep_approvalid
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_flow_approvalstep_approvalid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_approvalid");
			this.SetAttributeValue("msdyn_flow_approvalstep_approvalid", value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_approvalid");
		}
	}
	
	/// <summary>
	/// Step model Lookup
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_model")]
	public Microsoft.Xrm.Sdk.EntityReference msdyn_flow_approvalstep_model
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_flow_approvalstep_model");
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_model");
			this.SetAttributeValue("msdyn_flow_approvalstep_model", value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_model");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_modeltype")]
	public string msdyn_flow_approvalstep_modeltype
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_flow_approvalstep_modeltype");
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_modeltype");
			this.SetAttributeValue("msdyn_flow_approvalstep_modeltype", value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_modeltype");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_number")]
	public System.Nullable<int> msdyn_flow_approvalstep_number
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("msdyn_flow_approvalstep_number");
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_number");
			this.SetAttributeValue("msdyn_flow_approvalstep_number", value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_number");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_result")]
	public string msdyn_flow_approvalstep_result
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_flow_approvalstep_result");
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_result");
			this.SetAttributeValue("msdyn_flow_approvalstep_result", value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_result");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_stage")]
	public virtual msdyn_flow_approvalstage? msdyn_flow_approvalstep_stage
	{
		get
		{
			return ((msdyn_flow_approvalstage?)(EntityOptionSetEnum.GetEnum(this, "msdyn_flow_approvalstep_stage")));
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_stage");
			this.SetAttributeValue("msdyn_flow_approvalstep_stage", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("msdyn_flow_approvalstep_stage");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstepid")]
	public System.Nullable<System.Guid> msdyn_flow_approvalstepId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_flow_approvalstepid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstepId");
			this.SetAttributeValue("msdyn_flow_approvalstepid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("msdyn_flow_approvalstepId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstepid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.msdyn_flow_approvalstepId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
	public string msdyn_Name
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_name");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Name");
			this.SetAttributeValue("msdyn_name", value);
			this.OnPropertyChanged("msdyn_Name");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the Approval Step
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual msdyn_flow_approvalstep_statecode? statecode
	{
		get
		{
			return ((msdyn_flow_approvalstep_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Approval Step
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual msdyn_flow_approvalstep_statuscode? statuscode
	{
		get
		{
			return ((msdyn_flow_approvalstep_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_flow_approvalstep_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalstep_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> msdyn_flow_approvalstep_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("msdyn_flow_approvalstep_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("msdyn_flow_approvalstep_AsyncOperations", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_flow_approvalstep_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalstep_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> msdyn_flow_approvalstep_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("msdyn_flow_approvalstep_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("msdyn_flow_approvalstep_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_flow_approvalstep_DuplicateBaseRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalstep_DuplicateBaseRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> msdyn_flow_approvalstep_DuplicateBaseRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("msdyn_flow_approvalstep_DuplicateBaseRecord", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_DuplicateBaseRecord");
			this.SetRelatedEntities<DuplicateRecord>("msdyn_flow_approvalstep_DuplicateBaseRecord", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_DuplicateBaseRecord");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_flow_approvalstep_DuplicateMatchingRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalstep_DuplicateMatchingRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> msdyn_flow_approvalstep_DuplicateMatchingRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("msdyn_flow_approvalstep_DuplicateMatchingRecord", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_DuplicateMatchingRecord");
			this.SetRelatedEntities<DuplicateRecord>("msdyn_flow_approvalstep_DuplicateMatchingRecord", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_DuplicateMatchingRecord");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_flow_approvalstep_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalstep_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> msdyn_flow_approvalstep_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("msdyn_flow_approvalstep_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("msdyn_flow_approvalstep_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_flow_approvalstep_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalstep_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> msdyn_flow_approvalstep_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("msdyn_flow_approvalstep_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("msdyn_flow_approvalstep_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_flow_approvalstep_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalstep_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> msdyn_flow_approvalstep_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("msdyn_flow_approvalstep_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("msdyn_flow_approvalstep_ProcessSession", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_flow_approvalstep_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalstep_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> msdyn_flow_approvalstep_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("msdyn_flow_approvalstep_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_SyncErrors");
			this.SetRelatedEntities<SyncError>("msdyn_flow_approvalstep_SyncErrors", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_flow_approvalstep_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalstep_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> msdyn_flow_approvalstep_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("msdyn_flow_approvalstep_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalstep_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("msdyn_flow_approvalstep_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalstep_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:1 business_unit_msdyn_flow_approvalstep
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_msdyn_flow_approvalstep")]
	public BusinessUnit business_unit_msdyn_flow_approvalstep
	{
		get
		{
			return this.GetRelatedEntity<BusinessUnit>("business_unit_msdyn_flow_approvalstep", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_flow_approvalstep_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_flow_approvalstep_createdby")]
	public SystemUser lk_msdyn_flow_approvalstep_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_flow_approvalstep_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_flow_approvalstep_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_flow_approvalstep_createdonbehalfby")]
	public SystemUser lk_msdyn_flow_approvalstep_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_flow_approvalstep_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_flow_approvalstep_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_flow_approvalstep_modifiedby")]
	public SystemUser lk_msdyn_flow_approvalstep_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_flow_approvalstep_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_flow_approvalstep_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_flow_approvalstep_modifiedonbehalfby")]
	public SystemUser lk_msdyn_flow_approvalstep_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_flow_approvalstep_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 msdyn_flow_actionapprovalmodelrelationship_approvalsteps
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_model")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_actionapprovalmodelrelationship_approvalsteps")]
	public msdyn_flow_actionapprovalmodel msdyn_flow_actionapprovalmodelrelationship_approvalsteps
	{
		get
		{
			return this.GetRelatedEntity<msdyn_flow_actionapprovalmodel>("msdyn_flow_actionapprovalmodelrelationship_approvalsteps", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_actionapprovalmodelrelationship_approvalsteps");
			this.SetRelatedEntity<msdyn_flow_actionapprovalmodel>("msdyn_flow_actionapprovalmodelrelationship_approvalsteps", null, value);
			this.OnPropertyChanged("msdyn_flow_actionapprovalmodelrelationship_approvalsteps");
		}
	}
	
	/// <summary>
	/// N:1 msdyn_flow_approvalrelationship_approvalsteps
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_approval")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_approvalrelationship_approvalsteps")]
	public msdyn_flow_approval msdyn_flow_approvalrelationship_approvalsteps
	{
		get
		{
			return this.GetRelatedEntity<msdyn_flow_approval>("msdyn_flow_approvalrelationship_approvalsteps", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_approvalrelationship_approvalsteps");
			this.SetRelatedEntity<msdyn_flow_approval>("msdyn_flow_approvalrelationship_approvalsteps", null, value);
			this.OnPropertyChanged("msdyn_flow_approvalrelationship_approvalsteps");
		}
	}
	
	/// <summary>
	/// N:1 msdyn_flow_awaitallactionapprovalmodelrelationship_approvalsteps
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_model")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_awaitallactionapprovalmodelrelationship_approvalsteps")]
	public msdyn_flow_awaitallactionapprovalmodel msdyn_flow_awaitallactionapprovalmodelrelationship_approvalsteps
	{
		get
		{
			return this.GetRelatedEntity<msdyn_flow_awaitallactionapprovalmodel>("msdyn_flow_awaitallactionapprovalmodelrelationship_approvalsteps", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_awaitallactionapprovalmodelrelationship_approvalsteps");
			this.SetRelatedEntity<msdyn_flow_awaitallactionapprovalmodel>("msdyn_flow_awaitallactionapprovalmodelrelationship_approvalsteps", null, value);
			this.OnPropertyChanged("msdyn_flow_awaitallactionapprovalmodelrelationship_approvalsteps");
		}
	}
	
	/// <summary>
	/// N:1 msdyn_flow_awaitallapprovalmodelrelationship_approvalsteps
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_model")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_awaitallapprovalmodelrelationship_approvalsteps")]
	public msdyn_flow_awaitallapprovalmodel msdyn_flow_awaitallapprovalmodelrelationship_approvalsteps
	{
		get
		{
			return this.GetRelatedEntity<msdyn_flow_awaitallapprovalmodel>("msdyn_flow_awaitallapprovalmodelrelationship_approvalsteps", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_awaitallapprovalmodelrelationship_approvalsteps");
			this.SetRelatedEntity<msdyn_flow_awaitallapprovalmodel>("msdyn_flow_awaitallapprovalmodelrelationship_approvalsteps", null, value);
			this.OnPropertyChanged("msdyn_flow_awaitallapprovalmodelrelationship_approvalsteps");
		}
	}
	
	/// <summary>
	/// N:1 msdyn_flow_basicapprovalmodelrelationship_approvalsteps
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_flow_approvalstep_model")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_flow_basicapprovalmodelrelationship_approvalsteps")]
	public msdyn_flow_basicapprovalmodel msdyn_flow_basicapprovalmodelrelationship_approvalsteps
	{
		get
		{
			return this.GetRelatedEntity<msdyn_flow_basicapprovalmodel>("msdyn_flow_basicapprovalmodelrelationship_approvalsteps", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_flow_basicapprovalmodelrelationship_approvalsteps");
			this.SetRelatedEntity<msdyn_flow_basicapprovalmodel>("msdyn_flow_basicapprovalmodelrelationship_approvalsteps", null, value);
			this.OnPropertyChanged("msdyn_flow_basicapprovalmodelrelationship_approvalsteps");
		}
	}
	
	/// <summary>
	/// N:1 owner_msdyn_flow_approvalstep
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_msdyn_flow_approvalstep")]
	public Owner owner_msdyn_flow_approvalstep
	{
		get
		{
			return this.GetRelatedEntity<Owner>("owner_msdyn_flow_approvalstep", null);
		}
		set
		{
			this.OnPropertyChanging("owner_msdyn_flow_approvalstep");
			this.SetRelatedEntity<Owner>("owner_msdyn_flow_approvalstep", null, value);
			this.OnPropertyChanged("owner_msdyn_flow_approvalstep");
		}
	}
	
	/// <summary>
	/// N:1 team_msdyn_flow_approvalstep
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_msdyn_flow_approvalstep")]
	public Team team_msdyn_flow_approvalstep
	{
		get
		{
			return this.GetRelatedEntity<Team>("team_msdyn_flow_approvalstep", null);
		}
	}
	
	/// <summary>
	/// N:1 user_msdyn_flow_approvalstep
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_msdyn_flow_approvalstep")]
	public SystemUser user_msdyn_flow_approvalstep
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("user_msdyn_flow_approvalstep", null);
		}
	}
}
#pragma warning restore CS1591
