#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the AI Optimization Private Data
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_aioptimizationprivatedata_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the AI Optimization Private Data
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_aioptimizationprivatedata_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_aioptimizationprivatedata")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class msdyn_AIOptimizationPrivateData : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public msdyn_AIOptimizationPrivateData() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "msdyn_aioptimizationprivatedata";
	
	public const string EntityLogicalCollectionName = "msdyn_aioptimizationprivatedatas";
	
	public const string EntitySetName = "msdyn_aioptimizationprivatedatas";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_aioptimizationprivatedataid")]
	public System.Nullable<System.Guid> msdyn_AIOptimizationPrivateDataId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_aioptimizationprivatedataid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_AIOptimizationPrivateDataId");
			this.SetAttributeValue("msdyn_aioptimizationprivatedataid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("msdyn_AIOptimizationPrivateDataId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_aioptimizationprivatedataid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.msdyn_AIOptimizationPrivateDataId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_currentgradient")]
	public string msdyn_CurrentGradient
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_currentgradient");
		}
		set
		{
			this.OnPropertyChanging("msdyn_CurrentGradient");
			this.SetAttributeValue("msdyn_currentgradient", value);
			this.OnPropertyChanged("msdyn_CurrentGradient");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_currenttestscores")]
	public string msdyn_CurrentTestScores
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_currenttestscores");
		}
		set
		{
			this.OnPropertyChanging("msdyn_CurrentTestScores");
			this.SetAttributeValue("msdyn_currenttestscores", value);
			this.OnPropertyChanged("msdyn_CurrentTestScores");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
	public string msdyn_Name
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_name");
		}
		set
		{
			this.OnPropertyChanging("msdyn_Name");
			this.SetAttributeValue("msdyn_name", value);
			this.OnPropertyChanged("msdyn_Name");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_tests")]
	public System.Nullable<System.Guid> msdyn_Tests
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_tests");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Status of the AI Optimization Private Data
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual msdyn_aioptimizationprivatedata_statecode? statecode
	{
		get
		{
			return ((msdyn_aioptimizationprivatedata_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the AI Optimization Private Data
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual msdyn_aioptimizationprivatedata_statuscode? statuscode
	{
		get
		{
			return ((msdyn_aioptimizationprivatedata_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> msdyn_aioptimizationprivatedata_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("msdyn_aioptimizationprivatedata_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("msdyn_aioptimizationprivatedata_AsyncOperations", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> msdyn_aioptimizationprivatedata_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("msdyn_aioptimizationprivatedata_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("msdyn_aioptimizationprivatedata_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_DuplicateBaseRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_DuplicateBaseRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> msdyn_aioptimizationprivatedata_DuplicateBaseRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("msdyn_aioptimizationprivatedata_DuplicateBaseRecord", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_DuplicateBaseRecord");
			this.SetRelatedEntities<DuplicateRecord>("msdyn_aioptimizationprivatedata_DuplicateBaseRecord", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_DuplicateBaseRecord");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_DuplicateMatchingRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_DuplicateMatchingRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> msdyn_aioptimizationprivatedata_DuplicateMatchingRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("msdyn_aioptimizationprivatedata_DuplicateMatchingRecord", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_DuplicateMatchingRecord");
			this.SetRelatedEntities<DuplicateRecord>("msdyn_aioptimizationprivatedata_DuplicateMatchingRecord", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_DuplicateMatchingRecord");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_FileAttachments
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_FileAttachments")]
	public System.Collections.Generic.IEnumerable<FileAttachment> msdyn_aioptimizationprivatedata_FileAttachments
	{
		get
		{
			return this.GetRelatedEntities<FileAttachment>("msdyn_aioptimizationprivatedata_FileAttachments", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_FileAttachments");
			this.SetRelatedEntities<FileAttachment>("msdyn_aioptimizationprivatedata_FileAttachments", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_FileAttachments");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> msdyn_aioptimizationprivatedata_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("msdyn_aioptimizationprivatedata_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("msdyn_aioptimizationprivatedata_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_msdyn_aioptimization
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_msdyn_aioptimization")]
	public System.Collections.Generic.IEnumerable<msdyn_AIOptimization> msdyn_aioptimizationprivatedata_msdyn_aioptimization
	{
		get
		{
			return this.GetRelatedEntities<msdyn_AIOptimization>("msdyn_aioptimizationprivatedata_msdyn_aioptimization", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_msdyn_aioptimization");
			this.SetRelatedEntities<msdyn_AIOptimization>("msdyn_aioptimizationprivatedata_msdyn_aioptimization", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_msdyn_aioptimization");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> msdyn_aioptimizationprivatedata_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("msdyn_aioptimizationprivatedata_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("msdyn_aioptimizationprivatedata_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> msdyn_aioptimizationprivatedata_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("msdyn_aioptimizationprivatedata_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("msdyn_aioptimizationprivatedata_ProcessSession", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> msdyn_aioptimizationprivatedata_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("msdyn_aioptimizationprivatedata_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_SyncErrors");
			this.SetRelatedEntities<SyncError>("msdyn_aioptimizationprivatedata_SyncErrors", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_aioptimizationprivatedata_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_aioptimizationprivatedata_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> msdyn_aioptimizationprivatedata_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("msdyn_aioptimizationprivatedata_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_aioptimizationprivatedata_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("msdyn_aioptimizationprivatedata_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("msdyn_aioptimizationprivatedata_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:1 business_unit_msdyn_aioptimizationprivatedata
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_msdyn_aioptimizationprivatedata")]
	public BusinessUnit business_unit_msdyn_aioptimizationprivatedata
	{
		get
		{
			return this.GetRelatedEntity<BusinessUnit>("business_unit_msdyn_aioptimizationprivatedata", null);
		}
	}
	
	/// <summary>
	/// N:1 FileAttachment_msdyn_AIOptimizationPrivateData_msdyn_Tests
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_tests")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("FileAttachment_msdyn_AIOptimizationPrivateData_msdyn_Tests")]
	public FileAttachment FileAttachment_msdyn_AIOptimizationPrivateData_msdyn_Tests
	{
		get
		{
			return this.GetRelatedEntity<FileAttachment>("FileAttachment_msdyn_AIOptimizationPrivateData_msdyn_Tests", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_aioptimizationprivatedata_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_aioptimizationprivatedata_createdby")]
	public SystemUser lk_msdyn_aioptimizationprivatedata_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_aioptimizationprivatedata_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_aioptimizationprivatedata_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_aioptimizationprivatedata_createdonbehalfby")]
	public SystemUser lk_msdyn_aioptimizationprivatedata_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_aioptimizationprivatedata_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_aioptimizationprivatedata_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_aioptimizationprivatedata_modifiedby")]
	public SystemUser lk_msdyn_aioptimizationprivatedata_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_aioptimizationprivatedata_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_aioptimizationprivatedata_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_aioptimizationprivatedata_modifiedonbehalfby")]
	public SystemUser lk_msdyn_aioptimizationprivatedata_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_aioptimizationprivatedata_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 owner_msdyn_aioptimizationprivatedata
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_msdyn_aioptimizationprivatedata")]
	public Owner owner_msdyn_aioptimizationprivatedata
	{
		get
		{
			return this.GetRelatedEntity<Owner>("owner_msdyn_aioptimizationprivatedata", null);
		}
		set
		{
			this.OnPropertyChanging("owner_msdyn_aioptimizationprivatedata");
			this.SetRelatedEntity<Owner>("owner_msdyn_aioptimizationprivatedata", null, value);
			this.OnPropertyChanged("owner_msdyn_aioptimizationprivatedata");
		}
	}
	
	/// <summary>
	/// N:1 team_msdyn_aioptimizationprivatedata
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_msdyn_aioptimizationprivatedata")]
	public Team team_msdyn_aioptimizationprivatedata
	{
		get
		{
			return this.GetRelatedEntity<Team>("team_msdyn_aioptimizationprivatedata", null);
		}
	}
	
	/// <summary>
	/// N:1 user_msdyn_aioptimizationprivatedata
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_msdyn_aioptimizationprivatedata")]
	public SystemUser user_msdyn_aioptimizationprivatedata
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("user_msdyn_aioptimizationprivatedata", null);
		}
	}
}
#pragma warning restore CS1591
