#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_solutioncomponentcountdatasource")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class msdyn_solutioncomponentcountdatasource : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public msdyn_solutioncomponentcountdatasource() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "msdyn_solutioncomponentcountdatasource";
	
	public const string EntityLogicalCollectionName = "msdyn_solutioncomponentcountdatasources";
	
	public const string EntitySetName = "msdyn_solutioncomponentcountdatasources";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
	public string msdyn_name
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_name");
		}
		set
		{
			this.OnPropertyChanging("msdyn_name");
			this.SetAttributeValue("msdyn_name", value);
			this.OnPropertyChanged("msdyn_name");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_solutioncomponentcountdatasourceid")]
	public System.Nullable<System.Guid> msdyn_solutioncomponentcountdatasourceId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_solutioncomponentcountdatasourceid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_solutioncomponentcountdatasourceId");
			this.SetAttributeValue("msdyn_solutioncomponentcountdatasourceid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("msdyn_solutioncomponentcountdatasourceId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_solutioncomponentcountdatasourceid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.msdyn_solutioncomponentcountdatasourceId = value;
		}
	}
	
	/// <summary>
	/// Unique identifier for the organization
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	public System.Nullable<System.Guid> OrganizationId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("organizationid");
		}
	}
}
#pragma warning restore CS1591
