#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the msdyn_dmsrequest
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_dmsrequest_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the msdyn_dmsrequest
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum msdyn_dmsrequest_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

/// <summary>
/// Table for Data Movement Service Requests
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_dmsrequest")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class msdyn_dmsrequest : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public msdyn_dmsrequest() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "msdyn_dmsrequest";
	
	public const string EntityLogicalCollectionName = "msdyn_dmsrequests";
	
	public const string EntitySetName = "msdyn_dmsrequests";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Json with property bag.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_additionalproperties")]
	public string msdyn_AdditionalProperties
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_additionalproperties");
		}
		set
		{
			this.OnPropertyChanging("msdyn_AdditionalProperties");
			this.SetAttributeValue("msdyn_additionalproperties", value);
			this.OnPropertyChanged("msdyn_AdditionalProperties");
		}
	}
	
	/// <summary>
	/// Dictionary of Entity Name and CDM Entity Information.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_cdmentityinformation")]
	public string msdyn_CdmEntityInformation
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_cdmentityinformation");
		}
		set
		{
			this.OnPropertyChanging("msdyn_CdmEntityInformation");
			this.SetAttributeValue("msdyn_cdmentityinformation", value);
			this.OnPropertyChanged("msdyn_CdmEntityInformation");
		}
	}
	
	/// <summary>
	/// Json with Mapping with Cdm entity and dataverse entity
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_cdmtodataverseentitymapping")]
	public string msdyn_CdmToDataverseEntityMapping
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_cdmtodataverseentitymapping");
		}
		set
		{
			this.OnPropertyChanging("msdyn_CdmToDataverseEntityMapping");
			this.SetAttributeValue("msdyn_cdmtodataverseentitymapping", value);
			this.OnPropertyChanged("msdyn_CdmToDataverseEntityMapping");
		}
	}
	
	/// <summary>
	/// Correlation Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_correlationid")]
	public string msdyn_CorrelationId
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_correlationid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_CorrelationId");
			this.SetAttributeValue("msdyn_correlationid", value);
			this.OnPropertyChanged("msdyn_CorrelationId");
		}
	}
	
	/// <summary>
	/// Datalake Folder Name 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_datalakefoldername")]
	public string msdyn_DatalakeFolderName
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_datalakefoldername");
		}
		set
		{
			this.OnPropertyChanging("msdyn_DatalakeFolderName");
			this.SetAttributeValue("msdyn_datalakefoldername", value);
			this.OnPropertyChanged("msdyn_DatalakeFolderName");
		}
	}
	
	/// <summary>
	/// Dictionary of Entity Name and Dataverse Entity Information.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_dataverseentityinformation")]
	public string msdyn_DataverseEntityInformation
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_dataverseentityinformation");
		}
		set
		{
			this.OnPropertyChanging("msdyn_DataverseEntityInformation");
			this.SetAttributeValue("msdyn_dataverseentityinformation", value);
			this.OnPropertyChanged("msdyn_DataverseEntityInformation");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_dmsrequestid")]
	public System.Nullable<System.Guid> msdyn_dmsrequestId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_dmsrequestid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequestId");
			this.SetAttributeValue("msdyn_dmsrequestid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("msdyn_dmsrequestId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_dmsrequestid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.msdyn_dmsrequestId = value;
		}
	}
	
	/// <summary>
	/// Model Json Path 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_modeljsonpath")]
	public string msdyn_ModelJsonPath
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_modeljsonpath");
		}
		set
		{
			this.OnPropertyChanging("msdyn_ModelJsonPath");
			this.SetAttributeValue("msdyn_modeljsonpath", value);
			this.OnPropertyChanged("msdyn_ModelJsonPath");
		}
	}
	
	/// <summary>
	/// Json with parameters specific to request type.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_requestparameters")]
	public string msdyn_RequestParameters
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_requestparameters");
		}
		set
		{
			this.OnPropertyChanging("msdyn_RequestParameters");
			this.SetAttributeValue("msdyn_requestparameters", value);
			this.OnPropertyChanged("msdyn_RequestParameters");
		}
	}
	
	/// <summary>
	/// Request Type
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_requesttype")]
	public string msdyn_RequestType
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_requesttype");
		}
		set
		{
			this.OnPropertyChanging("msdyn_RequestType");
			this.SetAttributeValue("msdyn_requesttype", value);
			this.OnPropertyChanged("msdyn_RequestType");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_requestuniquename")]
	public string msdyn_RequestUniqueName
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_requestuniquename");
		}
		set
		{
			this.OnPropertyChanging("msdyn_RequestUniqueName");
			this.SetAttributeValue("msdyn_requestuniquename", value);
			this.OnPropertyChanged("msdyn_RequestUniqueName");
		}
	}
	
	/// <summary>
	/// User Object Id 
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_userobjectid")]
	public string msdyn_UserObjectId
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_userobjectid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_UserObjectId");
			this.SetAttributeValue("msdyn_userobjectid", value);
			this.OnPropertyChanged("msdyn_UserObjectId");
		}
	}
	
	/// <summary>
	/// User Tenant Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_usertenantid")]
	public string msdyn_UserTenantId
	{
		get
		{
			return this.GetAttributeValue<string>("msdyn_usertenantid");
		}
		set
		{
			this.OnPropertyChanging("msdyn_UserTenantId");
			this.SetAttributeValue("msdyn_usertenantid", value);
			this.OnPropertyChanged("msdyn_UserTenantId");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Status of the msdyn_dmsrequest
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual msdyn_dmsrequest_statecode? statecode
	{
		get
		{
			return ((msdyn_dmsrequest_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the msdyn_dmsrequest
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual msdyn_dmsrequest_statuscode? statuscode
	{
		get
		{
			return ((msdyn_dmsrequest_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dmsrequest_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dmsrequest_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> msdyn_dmsrequest_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("msdyn_dmsrequest_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequest_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("msdyn_dmsrequest_AsyncOperations", null, value);
			this.OnPropertyChanged("msdyn_dmsrequest_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dmsrequest_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dmsrequest_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> msdyn_dmsrequest_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("msdyn_dmsrequest_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequest_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("msdyn_dmsrequest_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("msdyn_dmsrequest_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dmsrequest_DuplicateBaseRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dmsrequest_DuplicateBaseRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> msdyn_dmsrequest_DuplicateBaseRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("msdyn_dmsrequest_DuplicateBaseRecord", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequest_DuplicateBaseRecord");
			this.SetRelatedEntities<DuplicateRecord>("msdyn_dmsrequest_DuplicateBaseRecord", null, value);
			this.OnPropertyChanged("msdyn_dmsrequest_DuplicateBaseRecord");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dmsrequest_DuplicateMatchingRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dmsrequest_DuplicateMatchingRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> msdyn_dmsrequest_DuplicateMatchingRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("msdyn_dmsrequest_DuplicateMatchingRecord", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequest_DuplicateMatchingRecord");
			this.SetRelatedEntities<DuplicateRecord>("msdyn_dmsrequest_DuplicateMatchingRecord", null, value);
			this.OnPropertyChanged("msdyn_dmsrequest_DuplicateMatchingRecord");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dmsrequest_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dmsrequest_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> msdyn_dmsrequest_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("msdyn_dmsrequest_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequest_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("msdyn_dmsrequest_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("msdyn_dmsrequest_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dmsrequest_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dmsrequest_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> msdyn_dmsrequest_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("msdyn_dmsrequest_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequest_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("msdyn_dmsrequest_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("msdyn_dmsrequest_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dmsrequest_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dmsrequest_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> msdyn_dmsrequest_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("msdyn_dmsrequest_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequest_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("msdyn_dmsrequest_ProcessSession", null, value);
			this.OnPropertyChanged("msdyn_dmsrequest_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dmsrequest_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dmsrequest_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> msdyn_dmsrequest_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("msdyn_dmsrequest_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequest_SyncErrors");
			this.SetRelatedEntities<SyncError>("msdyn_dmsrequest_SyncErrors", null, value);
			this.OnPropertyChanged("msdyn_dmsrequest_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_dmsrequest_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_dmsrequest_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> msdyn_dmsrequest_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("msdyn_dmsrequest_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_dmsrequest_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("msdyn_dmsrequest_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("msdyn_dmsrequest_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// 1:N msdyn_uploadrequest_jobstatus
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_uploadrequest_jobstatus")]
	public System.Collections.Generic.IEnumerable<msdyn_dmsrequeststatus> msdyn_uploadrequest_jobstatus
	{
		get
		{
			return this.GetRelatedEntities<msdyn_dmsrequeststatus>("msdyn_uploadrequest_jobstatus", null);
		}
		set
		{
			this.OnPropertyChanging("msdyn_uploadrequest_jobstatus");
			this.SetRelatedEntities<msdyn_dmsrequeststatus>("msdyn_uploadrequest_jobstatus", null, value);
			this.OnPropertyChanged("msdyn_uploadrequest_jobstatus");
		}
	}
	
	/// <summary>
	/// N:1 business_unit_msdyn_dmsrequest
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_msdyn_dmsrequest")]
	public BusinessUnit business_unit_msdyn_dmsrequest
	{
		get
		{
			return this.GetRelatedEntity<BusinessUnit>("business_unit_msdyn_dmsrequest", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_dmsrequest_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_dmsrequest_createdby")]
	public SystemUser lk_msdyn_dmsrequest_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_dmsrequest_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_dmsrequest_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_dmsrequest_createdonbehalfby")]
	public SystemUser lk_msdyn_dmsrequest_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_dmsrequest_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_dmsrequest_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_dmsrequest_modifiedby")]
	public SystemUser lk_msdyn_dmsrequest_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_dmsrequest_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_msdyn_dmsrequest_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_dmsrequest_modifiedonbehalfby")]
	public SystemUser lk_msdyn_dmsrequest_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_msdyn_dmsrequest_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 owner_msdyn_dmsrequest
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_msdyn_dmsrequest")]
	public Owner owner_msdyn_dmsrequest
	{
		get
		{
			return this.GetRelatedEntity<Owner>("owner_msdyn_dmsrequest", null);
		}
		set
		{
			this.OnPropertyChanging("owner_msdyn_dmsrequest");
			this.SetRelatedEntity<Owner>("owner_msdyn_dmsrequest", null, value);
			this.OnPropertyChanged("owner_msdyn_dmsrequest");
		}
	}
	
	/// <summary>
	/// N:1 team_msdyn_dmsrequest
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_msdyn_dmsrequest")]
	public Team team_msdyn_dmsrequest
	{
		get
		{
			return this.GetRelatedEntity<Team>("team_msdyn_dmsrequest", null);
		}
	}
	
	/// <summary>
	/// N:1 user_msdyn_dmsrequest
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_msdyn_dmsrequest")]
	public SystemUser user_msdyn_dmsrequest
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("user_msdyn_dmsrequest", null);
		}
	}
}
#pragma warning restore CS1591
