#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Multi Entity Search.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("multientitysearch")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class MultiEntitySearch : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public MultiEntitySearch() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "multientitysearch";
	
	public const string EntityLogicalCollectionName = "multientitysearches";
	
	public const string EntitySetName = "multientitysearches";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Shows who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Shows who created the record on behalf of another user.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Shows the multiple entity search.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("multientitysearchid")]
	public System.Nullable<System.Guid> MultiEntitySearchId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("multientitysearchid");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("multientitysearchid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			base.Id = value;
		}
	}
	
	/// <summary>
	/// Shows the name of the multiple entity search.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string Name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N multientitysearch_multientitysearchentities
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("multientitysearch_multientitysearchentities")]
	public System.Collections.Generic.IEnumerable<MultiEntitySearchEntities> multientitysearch_multientitysearchentities
	{
		get
		{
			return this.GetRelatedEntities<MultiEntitySearchEntities>("multientitysearch_multientitysearchentities", null);
		}
		set
		{
			this.OnPropertyChanging("multientitysearch_multientitysearchentities");
			this.SetRelatedEntities<MultiEntitySearchEntities>("multientitysearch_multientitysearchentities", null, value);
			this.OnPropertyChanged("multientitysearch_multientitysearchentities");
		}
	}
	
	/// <summary>
	/// N:1 multientitysearch_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("multientitysearch_createdby")]
	public SystemUser multientitysearch_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("multientitysearch_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 multientitysearch_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("multientitysearch_createdonbehalfby")]
	public SystemUser multientitysearch_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("multientitysearch_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 multientitysearch_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("multientitysearch_modifiedby")]
	public SystemUser multientitysearch_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("multientitysearch_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 multientitysearch_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("multientitysearch_modifiedonbehalfby")]
	public SystemUser multientitysearch_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("multientitysearch_modifiedonbehalfby", null);
		}
	}
}
#pragma warning restore CS1591
