#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the PDF Setting
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum pdfsetting_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the PDF Setting
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum pdfsetting_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

/// <summary>
/// PDF Settings to save enabled pdf entities
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("pdfsetting")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class PDFSetting : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public PDFSetting() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "pdfsetting";
	
	public const string EntityLogicalCollectionName = "pdfsettings";
	
	public const string EntitySetName = "pdfsettings";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// The name of the entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityname")]
	public string entityname
	{
		get
		{
			return this.GetAttributeValue<string>("entityname");
		}
		set
		{
			this.OnPropertyChanging("entityname");
			this.SetAttributeValue("entityname", value);
			this.OnPropertyChanged("entityname");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Contains true or false for enabled and disabled entities respectively
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ispdfsettingenabled")]
	public System.Nullable<bool> ispdfsettingenabled
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ispdfsettingenabled");
		}
		set
		{
			this.OnPropertyChanging("ispdfsettingenabled");
			this.SetAttributeValue("ispdfsettingenabled", value);
			this.OnPropertyChanged("ispdfsettingenabled");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pdfsettingid")]
	public System.Nullable<System.Guid> PDFSettingId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("pdfsettingid");
		}
		set
		{
			this.OnPropertyChanging("PDFSettingId");
			this.SetAttributeValue("pdfsettingid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("PDFSettingId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pdfsettingid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.PDFSettingId = value;
		}
	}
	
	/// <summary>
	/// Column to save PDF Settings in Json
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("pdfsettingsjson")]
	public string pdfsettingsjson
	{
		get
		{
			return this.GetAttributeValue<string>("pdfsettingsjson");
		}
		set
		{
			this.OnPropertyChanging("pdfsettingsjson");
			this.SetAttributeValue("pdfsettingsjson", value);
			this.OnPropertyChanged("pdfsettingsjson");
		}
	}
	
	/// <summary>
	/// Status of the pdfsetting
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual pdfsetting_statecode? statecode
	{
		get
		{
			return ((pdfsetting_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the pdfsetting
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual pdfsetting_statuscode? statuscode
	{
		get
		{
			return ((pdfsetting_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N pdfsetting_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pdfsetting_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> pdfsetting_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("pdfsetting_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("pdfsetting_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("pdfsetting_AsyncOperations", null, value);
			this.OnPropertyChanged("pdfsetting_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N pdfsetting_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pdfsetting_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> pdfsetting_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("pdfsetting_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("pdfsetting_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("pdfsetting_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("pdfsetting_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N pdfsetting_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pdfsetting_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> pdfsetting_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("pdfsetting_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("pdfsetting_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("pdfsetting_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("pdfsetting_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N pdfsetting_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pdfsetting_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> pdfsetting_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("pdfsetting_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("pdfsetting_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("pdfsetting_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("pdfsetting_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N pdfsetting_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pdfsetting_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> pdfsetting_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("pdfsetting_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("pdfsetting_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("pdfsetting_ProcessSession", null, value);
			this.OnPropertyChanged("pdfsetting_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N pdfsetting_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pdfsetting_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> pdfsetting_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("pdfsetting_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("pdfsetting_SyncErrors");
			this.SetRelatedEntities<SyncError>("pdfsetting_SyncErrors", null, value);
			this.OnPropertyChanged("pdfsetting_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N pdfsetting_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("pdfsetting_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> pdfsetting_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("pdfsetting_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("pdfsetting_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("pdfsetting_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("pdfsetting_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:1 business_unit_pdfsetting
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_pdfsetting")]
	public BusinessUnit business_unit_pdfsetting
	{
		get
		{
			return this.GetRelatedEntity<BusinessUnit>("business_unit_pdfsetting", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_pdfsetting_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_pdfsetting_createdby")]
	public SystemUser lk_pdfsetting_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_pdfsetting_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_pdfsetting_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_pdfsetting_createdonbehalfby")]
	public SystemUser lk_pdfsetting_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_pdfsetting_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_pdfsetting_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_pdfsetting_modifiedby")]
	public SystemUser lk_pdfsetting_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_pdfsetting_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_pdfsetting_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_pdfsetting_modifiedonbehalfby")]
	public SystemUser lk_pdfsetting_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_pdfsetting_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 owner_pdfsetting
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_pdfsetting")]
	public Owner owner_pdfsetting
	{
		get
		{
			return this.GetRelatedEntity<Owner>("owner_pdfsetting", null);
		}
		set
		{
			this.OnPropertyChanging("owner_pdfsetting");
			this.SetRelatedEntity<Owner>("owner_pdfsetting", null, value);
			this.OnPropertyChanged("owner_pdfsetting");
		}
	}
	
	/// <summary>
	/// N:1 team_pdfsetting
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_pdfsetting")]
	public Team team_pdfsetting
	{
		get
		{
			return this.GetRelatedEntity<Team>("team_pdfsetting", null);
		}
	}
	
	/// <summary>
	/// N:1 user_pdfsetting
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_pdfsetting")]
	public SystemUser user_pdfsetting
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("user_pdfsetting", null);
		}
	}
}
#pragma warning restore CS1591
