#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Power Pages Site
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum powerpagesite_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Power Pages Site
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum powerpagesite_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("powerpagesite")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class powerpagesite : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public powerpagesite() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "powerpagesite";
	
	public const string EntityLogicalCollectionName = "powerpagesites";
	
	public const string EntitySetName = "powerpagesites";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("content")]
	public string content
	{
		get
		{
			return this.GetAttributeValue<string>("content");
		}
		set
		{
			this.OnPropertyChanging("content");
			this.SetAttributeValue("content", value);
			this.OnPropertyChanged("content");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// This number indicates the active data model version for the portal.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("datamodelversion")]
	public string datamodelversion
	{
		get
		{
			return this.GetAttributeValue<string>("datamodelversion");
		}
		set
		{
			this.OnPropertyChanging("datamodelversion");
			this.SetAttributeValue("datamodelversion", value);
			this.OnPropertyChanged("datamodelversion");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// The name of the custom entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
		set
		{
			this.OnPropertyChanging("name");
			this.SetAttributeValue("name", value);
			this.OnPropertyChanged("name");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Owner Id
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier for the business unit that owns the record
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier for the team that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier for the user that owns the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagesiteid")]
	public System.Nullable<System.Guid> powerpagesiteId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("powerpagesiteid");
		}
		set
		{
			this.OnPropertyChanging("powerpagesiteId");
			this.SetAttributeValue("powerpagesiteid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("powerpagesiteId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagesiteid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.powerpagesiteId = value;
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("powerpagesitetype")]
	public virtual powerpagesitetype? powerpagesitetype
	{
		get
		{
			return ((powerpagesitetype?)(EntityOptionSetEnum.GetEnum(this, "powerpagesitetype")));
		}
		set
		{
			this.OnPropertyChanging("powerpagesitetype");
			this.SetAttributeValue("powerpagesitetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("powerpagesitetype");
		}
	}
	
	/// <summary>
	/// Tracks the primary domain name of the Portal
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primarydomainname")]
	public string primarydomainname
	{
		get
		{
			return this.GetAttributeValue<string>("primarydomainname");
		}
		set
		{
			this.OnPropertyChanging("primarydomainname");
			this.SetAttributeValue("primarydomainname", value);
			this.OnPropertyChanged("primarydomainname");
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Status of the Power Pages Site
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual powerpagesite_statecode? statecode
	{
		get
		{
			return ((powerpagesite_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Power Pages Site
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual powerpagesite_statuscode? statuscode
	{
		get
		{
			return ((powerpagesite_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N Comment_Artifact_PowerPageSite
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("Comment_Artifact_PowerPageSite")]
	public System.Collections.Generic.IEnumerable<Comment> Comment_Artifact_PowerPageSite
	{
		get
		{
			return this.GetRelatedEntities<Comment>("Comment_Artifact_PowerPageSite", null);
		}
		set
		{
			this.OnPropertyChanging("Comment_Artifact_PowerPageSite");
			this.SetRelatedEntities<Comment>("Comment_Artifact_PowerPageSite", null, value);
			this.OnPropertyChanged("Comment_Artifact_PowerPageSite");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> powerpagesite_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("powerpagesite_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("powerpagesite_AsyncOperations", null, value);
			this.OnPropertyChanged("powerpagesite_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> powerpagesite_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("powerpagesite_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("powerpagesite_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("powerpagesite_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> powerpagesite_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("powerpagesite_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("powerpagesite_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("powerpagesite_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_mspp_websiteid_adx_invitation
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_mspp_websiteid_adx_invitation")]
	public System.Collections.Generic.IEnumerable<adx_invitation> powerpagesite_mspp_websiteid_adx_invitation
	{
		get
		{
			return this.GetRelatedEntities<adx_invitation>("powerpagesite_mspp_websiteid_adx_invitation", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_mspp_websiteid_adx_invitation");
			this.SetRelatedEntities<adx_invitation>("powerpagesite_mspp_websiteid_adx_invitation", null, value);
			this.OnPropertyChanged("powerpagesite_mspp_websiteid_adx_invitation");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_powerpagecomponent_powerpagesiteid
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_powerpagecomponent_powerpagesiteid")]
	public System.Collections.Generic.IEnumerable<powerpagecomponent> powerpagesite_powerpagecomponent_powerpagesiteid
	{
		get
		{
			return this.GetRelatedEntities<powerpagecomponent>("powerpagesite_powerpagecomponent_powerpagesiteid", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_powerpagecomponent_powerpagesiteid");
			this.SetRelatedEntities<powerpagecomponent>("powerpagesite_powerpagecomponent_powerpagesiteid", null, value);
			this.OnPropertyChanged("powerpagesite_powerpagecomponent_powerpagesiteid");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_powerpagesitelanguage_powerpagesiteid
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_powerpagesitelanguage_powerpagesiteid")]
	public System.Collections.Generic.IEnumerable<powerpagesitelanguage> powerpagesite_powerpagesitelanguage_powerpagesiteid
	{
		get
		{
			return this.GetRelatedEntities<powerpagesitelanguage>("powerpagesite_powerpagesitelanguage_powerpagesiteid", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_powerpagesitelanguage_powerpagesiteid");
			this.SetRelatedEntities<powerpagesitelanguage>("powerpagesite_powerpagesitelanguage_powerpagesiteid", null, value);
			this.OnPropertyChanged("powerpagesite_powerpagesitelanguage_powerpagesiteid");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_powerpagesitepublished_powerpagesiteid
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_powerpagesitepublished_powerpagesiteid")]
	public System.Collections.Generic.IEnumerable<powerpagesitepublished> powerpagesite_powerpagesitepublished_powerpagesiteid
	{
		get
		{
			return this.GetRelatedEntities<powerpagesitepublished>("powerpagesite_powerpagesitepublished_powerpagesiteid", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_powerpagesitepublished_powerpagesiteid");
			this.SetRelatedEntities<powerpagesitepublished>("powerpagesite_powerpagesitepublished_powerpagesiteid", null, value);
			this.OnPropertyChanged("powerpagesite_powerpagesitepublished_powerpagesiteid");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_powerpagessourcefile_powerpagesiteid
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_powerpagessourcefile_powerpagesiteid")]
	public System.Collections.Generic.IEnumerable<powerpagessourcefile> powerpagesite_powerpagessourcefile_powerpagesiteid
	{
		get
		{
			return this.GetRelatedEntities<powerpagessourcefile>("powerpagesite_powerpagessourcefile_powerpagesiteid", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_powerpagessourcefile_powerpagesiteid");
			this.SetRelatedEntities<powerpagessourcefile>("powerpagesite_powerpagessourcefile_powerpagesiteid", null, value);
			this.OnPropertyChanged("powerpagesite_powerpagessourcefile_powerpagesiteid");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> powerpagesite_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("powerpagesite_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("powerpagesite_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("powerpagesite_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> powerpagesite_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("powerpagesite_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("powerpagesite_ProcessSession", null, value);
			this.OnPropertyChanged("powerpagesite_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> powerpagesite_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("powerpagesite_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_SyncErrors");
			this.SetRelatedEntities<SyncError>("powerpagesite_SyncErrors", null, value);
			this.OnPropertyChanged("powerpagesite_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N powerpagesite_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> powerpagesite_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("powerpagesite_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("powerpagesite_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("powerpagesite_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:N powerpagesite_dvfilesearch
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_dvfilesearch")]
	public System.Collections.Generic.IEnumerable<DVFileSearch> powerpagesite_dvfilesearch
	{
		get
		{
			return this.GetRelatedEntities<DVFileSearch>("powerpagesite_dvfilesearch", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_dvfilesearch");
			this.SetRelatedEntities<DVFileSearch>("powerpagesite_dvfilesearch", null, value);
			this.OnPropertyChanged("powerpagesite_dvfilesearch");
		}
	}
	
	/// <summary>
	/// N:N powerpagesite_dvtablesearch
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("powerpagesite_dvtablesearch")]
	public System.Collections.Generic.IEnumerable<DVTableSearch> powerpagesite_dvtablesearch
	{
		get
		{
			return this.GetRelatedEntities<DVTableSearch>("powerpagesite_dvtablesearch", null);
		}
		set
		{
			this.OnPropertyChanging("powerpagesite_dvtablesearch");
			this.SetRelatedEntities<DVTableSearch>("powerpagesite_dvtablesearch", null, value);
			this.OnPropertyChanged("powerpagesite_dvtablesearch");
		}
	}
	
	/// <summary>
	/// N:1 business_unit_powerpagesite
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_powerpagesite")]
	public BusinessUnit business_unit_powerpagesite
	{
		get
		{
			return this.GetRelatedEntity<BusinessUnit>("business_unit_powerpagesite", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_powerpagesite_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_powerpagesite_createdby")]
	public SystemUser lk_powerpagesite_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_powerpagesite_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_powerpagesite_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_powerpagesite_createdonbehalfby")]
	public SystemUser lk_powerpagesite_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_powerpagesite_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_powerpagesite_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_powerpagesite_modifiedby")]
	public SystemUser lk_powerpagesite_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_powerpagesite_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_powerpagesite_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_powerpagesite_modifiedonbehalfby")]
	public SystemUser lk_powerpagesite_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_powerpagesite_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 owner_powerpagesite
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_powerpagesite")]
	public Owner owner_powerpagesite
	{
		get
		{
			return this.GetRelatedEntity<Owner>("owner_powerpagesite", null);
		}
		set
		{
			this.OnPropertyChanging("owner_powerpagesite");
			this.SetRelatedEntity<Owner>("owner_powerpagesite", null, value);
			this.OnPropertyChanged("owner_powerpagesite");
		}
	}
	
	/// <summary>
	/// N:1 team_powerpagesite
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_powerpagesite")]
	public Team team_powerpagesite
	{
		get
		{
			return this.GetRelatedEntity<Team>("team_powerpagesite", null);
		}
	}
	
	/// <summary>
	/// N:1 user_powerpagesite
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_powerpagesite")]
	public SystemUser user_powerpagesite
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("user_powerpagesite", null);
		}
	}
}
#pragma warning restore CS1591
