#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum solutioncomponentconfiguration_fileformat
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	xml = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	json = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum solutioncomponentconfiguration_filescope
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	None = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Individual = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Global = 2,
}

/// <summary>
/// Status of the Solution Component Configuration
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum solutioncomponentconfiguration_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Solution Component Configuration
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum solutioncomponentconfiguration_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("solutioncomponentconfiguration")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class solutioncomponentconfiguration : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public solutioncomponentconfiguration() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "solutioncomponentconfiguration";
	
	public const string EntityLogicalCollectionName = "solutioncomponentconfigurations";
	
	public const string EntitySetName = "solutioncomponentconfigurations";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Boolean that indicates if an export key without a prefix is allowed.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("allowexportkeywithoutprefix")]
	public System.Nullable<bool> AllowExportKeyWithoutPrefix
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("allowexportkeywithoutprefix");
		}
		set
		{
			this.OnPropertyChanging("AllowExportKeyWithoutPrefix");
			this.SetAttributeValue("allowexportkeywithoutprefix", value);
			this.OnPropertyChanged("AllowExportKeyWithoutPrefix");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentidunique")]
	public System.Nullable<System.Guid> ComponentIdUnique
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("componentidunique");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public virtual componentstate? ComponentState
	{
		get
		{
			return ((componentstate?)(EntityOptionSetEnum.GetEnum(this, "componentstate")));
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Comma separated list of required components not supported for automatic dependency removal
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dependencyremovaldisabledforcomponents")]
	public string DependencyRemovalDisabledForComponents
	{
		get
		{
			return this.GetAttributeValue<string>("dependencyremovaldisabledforcomponents");
		}
		set
		{
			this.OnPropertyChanging("DependencyRemovalDisabledForComponents");
			this.SetAttributeValue("dependencyremovaldisabledforcomponents", value);
			this.OnPropertyChanged("DependencyRemovalDisabledForComponents");
		}
	}
	
	/// <summary>
	/// Unique identifier for Entity associated with Solution Component Configuration.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityid")]
	public Microsoft.Xrm.Sdk.EntityReference EntityId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("entityid");
		}
		set
		{
			this.OnPropertyChanging("EntityId");
			this.SetAttributeValue("entityid", value);
			this.OnPropertyChanged("EntityId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fileformat")]
	public virtual solutioncomponentconfiguration_fileformat? FileFormat
	{
		get
		{
			return ((solutioncomponentconfiguration_fileformat?)(EntityOptionSetEnum.GetEnum(this, "fileformat")));
		}
		set
		{
			this.OnPropertyChanging("FileFormat");
			this.SetAttributeValue("fileformat", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("FileFormat");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("filescope")]
	public virtual solutioncomponentconfiguration_filescope? FileScope
	{
		get
		{
			return ((solutioncomponentconfiguration_filescope?)(EntityOptionSetEnum.GetEnum(this, "filescope")));
		}
		set
		{
			this.OnPropertyChanging("FileScope");
			this.SetAttributeValue("filescope", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("FileScope");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Boolean that indicates if invoke substitution API will be used on component on template mode import
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("invokesubstitution")]
	public System.Nullable<bool> InvokeSubstitution
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("invokesubstitution");
		}
		set
		{
			this.OnPropertyChanging("InvokeSubstitution");
			this.SetAttributeValue("invokesubstitution", value);
			this.OnPropertyChanged("InvokeSubstitution");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("iscustomizable")]
	public Microsoft.Xrm.Sdk.BooleanManagedProperty IsCustomizable
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.BooleanManagedProperty>("iscustomizable");
		}
		set
		{
			this.OnPropertyChanging("IsCustomizable");
			this.SetAttributeValue("iscustomizable", value);
			this.OnPropertyChanged("IsCustomizable");
		}
	}
	
	/// <summary>
	/// Boolean that indicates if the component has user interface enabled.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdisplayable")]
	public System.Nullable<bool> isdisplayable
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("isdisplayable");
		}
		set
		{
			this.OnPropertyChanging("isdisplayable");
			this.SetAttributeValue("isdisplayable", value);
			this.OnPropertyChanged("isdisplayable");
		}
	}
	
	/// <summary>
	/// Indicates whether the solution component is part of a managed solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
	public System.Nullable<bool> IsManaged
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
		}
	}
	
	/// <summary>
	/// Boolean that indicates if the component is 1-1 child component.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isonetoonechildcomponent")]
	public System.Nullable<bool> IsOneToOneChildComponent
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("isonetoonechildcomponent");
		}
		set
		{
			this.OnPropertyChanging("IsOneToOneChildComponent");
			this.SetAttributeValue("isonetoonechildcomponent", value);
			this.OnPropertyChanged("IsOneToOneChildComponent");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("issoftdeleteenabled")]
	public System.Nullable<bool> IsSoftDeleteEnabled
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("issoftdeleteenabled");
		}
		set
		{
			this.OnPropertyChanging("IsSoftDeleteEnabled");
			this.SetAttributeValue("issoftdeleteenabled", value);
			this.OnPropertyChanged("IsSoftDeleteEnabled");
		}
	}
	
	/// <summary>
	/// Boolean that indicates if the component should be versioned.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isversioningenabled")]
	public System.Nullable<bool> IsVersioningEnabled
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("isversioningenabled");
		}
		set
		{
			this.OnPropertyChanging("IsVersioningEnabled");
			this.SetAttributeValue("isversioningenabled", value);
			this.OnPropertyChanged("IsVersioningEnabled");
		}
	}
	
	/// <summary>
	/// Boolean that indicates if the component should retain its unmanaged customization after conversion.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("keepactivecustomizationafterconversion")]
	public System.Nullable<bool> KeepActiveCustomizationAfterConversion
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<bool>>("keepactivecustomizationafterconversion");
		}
		set
		{
			this.OnPropertyChanging("KeepActiveCustomizationAfterConversion");
			this.SetAttributeValue("keepactivecustomizationafterconversion", value);
			this.OnPropertyChanged("KeepActiveCustomizationAfterConversion");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// The name of the custom entity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
		set
		{
			this.OnPropertyChanging("name");
			this.SetAttributeValue("name", value);
			this.OnPropertyChanged("name");
		}
	}
	
	/// <summary>
	/// Unique identifier for the organization
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	public Microsoft.Xrm.Sdk.EntityReference OrganizationId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutioncomponentconfigurationid")]
	public System.Nullable<System.Guid> solutioncomponentconfigurationId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutioncomponentconfigurationid");
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfigurationId");
			this.SetAttributeValue("solutioncomponentconfigurationid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("solutioncomponentconfigurationId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutioncomponentconfigurationid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.solutioncomponentconfigurationId = value;
		}
	}
	
	/// <summary>
	/// Unique identifier of the associated solution.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
	}
	
	/// <summary>
	/// Status of the Solution Component Configuration
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual solutioncomponentconfiguration_statecode? statecode
	{
		get
		{
			return ((solutioncomponentconfiguration_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the Solution Component Configuration
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual solutioncomponentconfiguration_statuscode? statuscode
	{
		get
		{
			return ((solutioncomponentconfiguration_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfig_solutioncomponentattrconfig
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfig_solutioncomponentattrconfig")]
	public System.Collections.Generic.IEnumerable<solutioncomponentattributeconfiguration> solutioncomponentconfig_solutioncomponentattrconfig
	{
		get
		{
			return this.GetRelatedEntities<solutioncomponentattributeconfiguration>("solutioncomponentconfig_solutioncomponentattrconfig", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfig_solutioncomponentattrconfig");
			this.SetRelatedEntities<solutioncomponentattributeconfiguration>("solutioncomponentconfig_solutioncomponentattrconfig", null, value);
			this.OnPropertyChanged("solutioncomponentconfig_solutioncomponentattrconfig");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfiguration_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfiguration_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> solutioncomponentconfiguration_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("solutioncomponentconfiguration_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfiguration_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("solutioncomponentconfiguration_AsyncOperations", null, value);
			this.OnPropertyChanged("solutioncomponentconfiguration_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfiguration_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfiguration_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> solutioncomponentconfiguration_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("solutioncomponentconfiguration_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfiguration_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("solutioncomponentconfiguration_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("solutioncomponentconfiguration_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfiguration_DuplicateBaseRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfiguration_DuplicateBaseRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> solutioncomponentconfiguration_DuplicateBaseRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("solutioncomponentconfiguration_DuplicateBaseRecord", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfiguration_DuplicateBaseRecord");
			this.SetRelatedEntities<DuplicateRecord>("solutioncomponentconfiguration_DuplicateBaseRecord", null, value);
			this.OnPropertyChanged("solutioncomponentconfiguration_DuplicateBaseRecord");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfiguration_DuplicateMatchingRecord
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfiguration_DuplicateMatchingRecord")]
	public System.Collections.Generic.IEnumerable<DuplicateRecord> solutioncomponentconfiguration_DuplicateMatchingRecord
	{
		get
		{
			return this.GetRelatedEntities<DuplicateRecord>("solutioncomponentconfiguration_DuplicateMatchingRecord", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfiguration_DuplicateMatchingRecord");
			this.SetRelatedEntities<DuplicateRecord>("solutioncomponentconfiguration_DuplicateMatchingRecord", null, value);
			this.OnPropertyChanged("solutioncomponentconfiguration_DuplicateMatchingRecord");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfiguration_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfiguration_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> solutioncomponentconfiguration_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("solutioncomponentconfiguration_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfiguration_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("solutioncomponentconfiguration_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("solutioncomponentconfiguration_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfiguration_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfiguration_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> solutioncomponentconfiguration_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("solutioncomponentconfiguration_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfiguration_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("solutioncomponentconfiguration_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("solutioncomponentconfiguration_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfiguration_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfiguration_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> solutioncomponentconfiguration_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("solutioncomponentconfiguration_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfiguration_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("solutioncomponentconfiguration_ProcessSession", null, value);
			this.OnPropertyChanged("solutioncomponentconfiguration_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfiguration_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfiguration_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> solutioncomponentconfiguration_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("solutioncomponentconfiguration_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfiguration_SyncErrors");
			this.SetRelatedEntities<SyncError>("solutioncomponentconfiguration_SyncErrors", null, value);
			this.OnPropertyChanged("solutioncomponentconfiguration_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N solutioncomponentconfiguration_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("solutioncomponentconfiguration_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> solutioncomponentconfiguration_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("solutioncomponentconfiguration_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("solutioncomponentconfiguration_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("solutioncomponentconfiguration_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("solutioncomponentconfiguration_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:1 entity_solutioncomponentconfiguration
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("entity_solutioncomponentconfiguration")]
	public Entity_Ent entity_solutioncomponentconfiguration
	{
		get
		{
			return this.GetRelatedEntity<Entity_Ent>("entity_solutioncomponentconfiguration", null);
		}
		set
		{
			this.OnPropertyChanging("entity_solutioncomponentconfiguration");
			this.SetRelatedEntity<Entity_Ent>("entity_solutioncomponentconfiguration", null, value);
			this.OnPropertyChanged("entity_solutioncomponentconfiguration");
		}
	}
	
	/// <summary>
	/// N:1 lk_solutioncomponentconfiguration_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_solutioncomponentconfiguration_createdby")]
	public SystemUser lk_solutioncomponentconfiguration_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_solutioncomponentconfiguration_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_solutioncomponentconfiguration_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_solutioncomponentconfiguration_createdonbehalfby")]
	public SystemUser lk_solutioncomponentconfiguration_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_solutioncomponentconfiguration_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_solutioncomponentconfiguration_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_solutioncomponentconfiguration_modifiedby")]
	public SystemUser lk_solutioncomponentconfiguration_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_solutioncomponentconfiguration_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_solutioncomponentconfiguration_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_solutioncomponentconfiguration_modifiedonbehalfby")]
	public SystemUser lk_solutioncomponentconfiguration_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_solutioncomponentconfiguration_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 organization_solutioncomponentconfiguration
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("organization_solutioncomponentconfiguration")]
	public Organization organization_solutioncomponentconfiguration
	{
		get
		{
			return this.GetRelatedEntity<Organization>("organization_solutioncomponentconfiguration", null);
		}
	}
}
#pragma warning restore CS1591
