#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Status of the Staged relationship
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum stagedviewattribute_statecode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 1,
}

/// <summary>
/// Reason for the status of the Staged relationship
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public enum stagedviewattribute_statuscode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	Inactive = 2,
}

/// <summary>
/// Stores staged replationship metadata to be processed asynchronous.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("stagedviewattribute")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class StagedViewAttribute : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public StagedViewAttribute() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "stagedviewattribute";
	
	public const string EntityLogicalCollectionName = "stagedviewattributes";
	
	public const string EntitySetName = "stagedviewattributes";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Identifier of the attribute.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("attributeid")]
	public System.Nullable<System.Guid> AttributeId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("attributeid");
		}
		set
		{
			this.OnPropertyChanging("AttributeId");
			this.SetAttributeValue("attributeid", value);
			this.OnPropertyChanged("AttributeId");
		}
	}
	
	/// <summary>
	/// Solution component state of view attribute.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
	public System.Nullable<int> ComponentState
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("componentstate");
		}
		set
		{
			this.OnPropertyChanging("ComponentState");
			this.SetAttributeValue("componentstate", value);
			this.OnPropertyChanged("ComponentState");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Sequence number of the import that created this record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
	public System.Nullable<int> ImportSequenceNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
		}
		set
		{
			this.OnPropertyChanging("ImportSequenceNumber");
			this.SetAttributeValue("importsequencenumber", value);
			this.OnPropertyChanged("ImportSequenceNumber");
		}
	}
	
	/// <summary>
	/// Metadata description of view attribute.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("metadatadescription")]
	public string MetadataDescription
	{
		get
		{
			return this.GetAttributeValue<string>("metadatadescription");
		}
		set
		{
			this.OnPropertyChanging("MetadataDescription");
			this.SetAttributeValue("metadatadescription", value);
			this.OnPropertyChanged("MetadataDescription");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Date and time when the record was modified.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who modified the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// The name of the view attribute.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
	public string Name
	{
		get
		{
			return this.GetAttributeValue<string>("name");
		}
		set
		{
			this.OnPropertyChanging("Name");
			this.SetAttributeValue("name", value);
			this.OnPropertyChanged("Name");
		}
	}
	
	/// <summary>
	/// Date and time that the record was migrated.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
	public System.Nullable<System.DateTime> OverriddenCreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
		}
		set
		{
			this.OnPropertyChanging("OverriddenCreatedOn");
			this.SetAttributeValue("overriddencreatedon", value);
			this.OnPropertyChanged("OverriddenCreatedOn");
		}
	}
	
	/// <summary>
	/// Overwrite time of the solution component view attribute.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
	public System.Nullable<System.DateTime> OverwriteTime
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
		}
		set
		{
			this.OnPropertyChanging("OverwriteTime");
			this.SetAttributeValue("overwritetime", value);
			this.OnPropertyChanged("OverwriteTime");
		}
	}
	
	/// <summary>
	/// Identifier of the relationship.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("relationshipid")]
	public System.Nullable<System.Guid> RelationshipId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("relationshipid");
		}
		set
		{
			this.OnPropertyChanging("RelationshipId");
			this.SetAttributeValue("relationshipid", value);
			this.OnPropertyChanged("RelationshipId");
		}
	}
	
	/// <summary>
	/// Identifier of the remote attribute.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("remoteattributeid")]
	public System.Nullable<System.Guid> RemoteAttributeId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("remoteattributeid");
		}
		set
		{
			this.OnPropertyChanging("RemoteAttributeId");
			this.SetAttributeValue("remoteattributeid", value);
			this.OnPropertyChanged("RemoteAttributeId");
		}
	}
	
	/// <summary>
	/// Identifier of the solution that contains view attribute.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
	public System.Nullable<System.Guid> SolutionId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
		}
		set
		{
			this.OnPropertyChanging("SolutionId");
			this.SetAttributeValue("solutionid", value);
			this.OnPropertyChanged("SolutionId");
		}
	}
	
	/// <summary>
	/// Unique identifier for entity instances.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stagedviewattributeid")]
	public System.Nullable<System.Guid> StagedViewAttributeId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("stagedviewattributeid");
		}
		set
		{
			this.OnPropertyChanging("StagedViewAttributeId");
			this.SetAttributeValue("stagedviewattributeid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("StagedViewAttributeId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stagedviewattributeid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.StagedViewAttributeId = value;
		}
	}
	
	/// <summary>
	/// A unique identifier used to tie together all objects staged within the same transaction.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stagingexecutioncontextid")]
	public System.Nullable<System.Guid> StagingExecutionContextId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("stagingexecutioncontextid");
		}
		set
		{
			this.OnPropertyChanging("StagingExecutionContextId");
			this.SetAttributeValue("stagingexecutioncontextid", value);
			this.OnPropertyChanged("StagingExecutionContextId");
		}
	}
	
	/// <summary>
	/// Status of the staged view attribute.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
	public virtual stagedviewattribute_statecode? statecode
	{
		get
		{
			return ((stagedviewattribute_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
		}
		set
		{
			this.OnPropertyChanging("statecode");
			this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statecode");
		}
	}
	
	/// <summary>
	/// Reason for the status of the staged view attribute.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
	public virtual stagedviewattribute_statuscode? statuscode
	{
		get
		{
			return ((stagedviewattribute_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
		}
		set
		{
			this.OnPropertyChanging("statuscode");
			this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			this.OnPropertyChanged("statuscode");
		}
	}
	
	/// <summary>
	/// For internal use only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
	public System.Nullable<int> TimeZoneRuleVersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
		}
		set
		{
			this.OnPropertyChanging("TimeZoneRuleVersionNumber");
			this.SetAttributeValue("timezoneruleversionnumber", value);
			this.OnPropertyChanged("TimeZoneRuleVersionNumber");
		}
	}
	
	/// <summary>
	/// Time zone code that was in use when the record was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
	public System.Nullable<int> UTCConversionTimeZoneCode
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
		}
		set
		{
			this.OnPropertyChanging("UTCConversionTimeZoneCode");
			this.SetAttributeValue("utcconversiontimezonecode", value);
			this.OnPropertyChanged("UTCConversionTimeZoneCode");
		}
	}
	
	/// <summary>
	/// Version Number
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// 1:N stagedviewattribute_AsyncOperations
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("stagedviewattribute_AsyncOperations")]
	public System.Collections.Generic.IEnumerable<AsyncOperation> stagedviewattribute_AsyncOperations
	{
		get
		{
			return this.GetRelatedEntities<AsyncOperation>("stagedviewattribute_AsyncOperations", null);
		}
		set
		{
			this.OnPropertyChanging("stagedviewattribute_AsyncOperations");
			this.SetRelatedEntities<AsyncOperation>("stagedviewattribute_AsyncOperations", null, value);
			this.OnPropertyChanged("stagedviewattribute_AsyncOperations");
		}
	}
	
	/// <summary>
	/// 1:N stagedviewattribute_BulkDeleteFailures
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("stagedviewattribute_BulkDeleteFailures")]
	public System.Collections.Generic.IEnumerable<BulkDeleteFailure> stagedviewattribute_BulkDeleteFailures
	{
		get
		{
			return this.GetRelatedEntities<BulkDeleteFailure>("stagedviewattribute_BulkDeleteFailures", null);
		}
		set
		{
			this.OnPropertyChanging("stagedviewattribute_BulkDeleteFailures");
			this.SetRelatedEntities<BulkDeleteFailure>("stagedviewattribute_BulkDeleteFailures", null, value);
			this.OnPropertyChanged("stagedviewattribute_BulkDeleteFailures");
		}
	}
	
	/// <summary>
	/// 1:N stagedviewattribute_MailboxTrackingFolders
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("stagedviewattribute_MailboxTrackingFolders")]
	public System.Collections.Generic.IEnumerable<MailboxTrackingFolder> stagedviewattribute_MailboxTrackingFolders
	{
		get
		{
			return this.GetRelatedEntities<MailboxTrackingFolder>("stagedviewattribute_MailboxTrackingFolders", null);
		}
		set
		{
			this.OnPropertyChanging("stagedviewattribute_MailboxTrackingFolders");
			this.SetRelatedEntities<MailboxTrackingFolder>("stagedviewattribute_MailboxTrackingFolders", null, value);
			this.OnPropertyChanged("stagedviewattribute_MailboxTrackingFolders");
		}
	}
	
	/// <summary>
	/// 1:N stagedviewattribute_PrincipalObjectAttributeAccesses
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("stagedviewattribute_PrincipalObjectAttributeAccesses")]
	public System.Collections.Generic.IEnumerable<PrincipalObjectAttributeAccess> stagedviewattribute_PrincipalObjectAttributeAccesses
	{
		get
		{
			return this.GetRelatedEntities<PrincipalObjectAttributeAccess>("stagedviewattribute_PrincipalObjectAttributeAccesses", null);
		}
		set
		{
			this.OnPropertyChanging("stagedviewattribute_PrincipalObjectAttributeAccesses");
			this.SetRelatedEntities<PrincipalObjectAttributeAccess>("stagedviewattribute_PrincipalObjectAttributeAccesses", null, value);
			this.OnPropertyChanged("stagedviewattribute_PrincipalObjectAttributeAccesses");
		}
	}
	
	/// <summary>
	/// 1:N stagedviewattribute_ProcessSession
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("stagedviewattribute_ProcessSession")]
	public System.Collections.Generic.IEnumerable<ProcessSession> stagedviewattribute_ProcessSession
	{
		get
		{
			return this.GetRelatedEntities<ProcessSession>("stagedviewattribute_ProcessSession", null);
		}
		set
		{
			this.OnPropertyChanging("stagedviewattribute_ProcessSession");
			this.SetRelatedEntities<ProcessSession>("stagedviewattribute_ProcessSession", null, value);
			this.OnPropertyChanged("stagedviewattribute_ProcessSession");
		}
	}
	
	/// <summary>
	/// 1:N stagedviewattribute_SyncErrors
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("stagedviewattribute_SyncErrors")]
	public System.Collections.Generic.IEnumerable<SyncError> stagedviewattribute_SyncErrors
	{
		get
		{
			return this.GetRelatedEntities<SyncError>("stagedviewattribute_SyncErrors", null);
		}
		set
		{
			this.OnPropertyChanging("stagedviewattribute_SyncErrors");
			this.SetRelatedEntities<SyncError>("stagedviewattribute_SyncErrors", null, value);
			this.OnPropertyChanged("stagedviewattribute_SyncErrors");
		}
	}
	
	/// <summary>
	/// 1:N stagedviewattribute_UserEntityInstanceDatas
	/// </summary>
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("stagedviewattribute_UserEntityInstanceDatas")]
	public System.Collections.Generic.IEnumerable<UserEntityInstanceData> stagedviewattribute_UserEntityInstanceDatas
	{
		get
		{
			return this.GetRelatedEntities<UserEntityInstanceData>("stagedviewattribute_UserEntityInstanceDatas", null);
		}
		set
		{
			this.OnPropertyChanging("stagedviewattribute_UserEntityInstanceDatas");
			this.SetRelatedEntities<UserEntityInstanceData>("stagedviewattribute_UserEntityInstanceDatas", null, value);
			this.OnPropertyChanged("stagedviewattribute_UserEntityInstanceDatas");
		}
	}
	
	/// <summary>
	/// N:1 lk_stagedviewattribute_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_stagedviewattribute_createdby")]
	public SystemUser lk_stagedviewattribute_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_stagedviewattribute_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_stagedviewattribute_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_stagedviewattribute_createdonbehalfby")]
	public SystemUser lk_stagedviewattribute_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_stagedviewattribute_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_stagedviewattribute_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_stagedviewattribute_modifiedby")]
	public SystemUser lk_stagedviewattribute_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_stagedviewattribute_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_stagedviewattribute_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_stagedviewattribute_modifiedonbehalfby")]
	public SystemUser lk_stagedviewattribute_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_stagedviewattribute_modifiedonbehalfby", null);
		}
	}
}
#pragma warning restore CS1591
