#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Activity that is delivered using UntrackedEmail protocols.
/// </summary>
[System.Runtime.Serialization.DataContractAttribute()]
[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("untrackedemail")]
[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
public partial class UntrackedEmail : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
{
	
	/// <summary>
	/// Default Constructor.
	/// </summary>
	public UntrackedEmail() : 
			base(EntityLogicalName)
	{
	}
	
	public const string EntityLogicalName = "untrackedemail";
	
	public const string EntityLogicalCollectionName = "untrackedemails";
	
	public const string EntitySetName = "untrackedemails";
	
	public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
	
	public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
	
	private void OnPropertyChanged(string propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void OnPropertyChanging(string propertyName)
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
		}
	}
	
	/// <summary>
	/// Unique identifier of untracked the email activity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activityid")]
	public System.Nullable<System.Guid> ActivityId
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.Guid>>("activityid");
		}
		set
		{
			this.OnPropertyChanging("ActivityId");
			this.SetAttributeValue("activityid", value);
			if (value.HasValue)
			{
				base.Id = value.Value;
			}
			else
			{
				base.Id = System.Guid.Empty;
			}
			this.OnPropertyChanged("ActivityId");
		}
	}
	
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activityid")]
	public override System.Guid Id
	{
		get
		{
			return base.Id;
		}
		set
		{
			this.ActivityId = value;
		}
	}
	
	/// <summary>
	/// Shows the type of activity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activitytypecode")]
	public string ActivityTypeCode
	{
		get
		{
			return this.GetAttributeValue<string>("activitytypecode");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who created the activity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
		}
	}
	
	/// <summary>
	/// Date and time when the activity was created.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
	public System.Nullable<System.DateTime> CreatedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
		}
	}
	
	/// <summary>
	/// Unique identifier of the delegate user who created the activitypointer.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
		}
	}
	
	/// <summary>
	/// Shows information about the untracked email. This field is read-only.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
	public string Description
	{
		get
		{
			return this.GetAttributeValue<string>("description");
		}
		set
		{
			this.OnPropertyChanging("Description");
			this.SetAttributeValue("description", value);
			this.OnPropertyChanged("Description");
		}
	}
	
	/// <summary>
	/// The message id of untracked email which is returned from Exchange Server.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangeitemid")]
	public string ExchangeItemId
	{
		get
		{
			return this.GetAttributeValue<string>("exchangeitemid");
		}
		set
		{
			this.OnPropertyChanging("ExchangeItemId");
			this.SetAttributeValue("exchangeitemid", value);
			this.OnPropertyChanged("ExchangeItemId");
		}
	}
	
	/// <summary>
	/// Shows the conversion rate of the record's currency. The exchange rate is used to convert all money fields in the record from the local currency to the system's default currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
	public System.Nullable<decimal> ExchangeRate
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
		}
	}
	
	/// <summary>
	/// Shows the web link of untracked email.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangeweblink")]
	public string ExchangeWebLink
	{
		get
		{
			return this.GetAttributeValue<string>("exchangeweblink");
		}
		set
		{
			this.OnPropertyChanging("ExchangeWebLink");
			this.SetAttributeValue("exchangeweblink", value);
			this.OnPropertyChanged("ExchangeWebLink");
		}
	}
	
	/// <summary>
	/// Shows who last updated the record.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
		}
	}
	
	/// <summary>
	/// Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Dynamics 365 options.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
	public System.Nullable<System.DateTime> ModifiedOn
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
		}
	}
	
	/// <summary>
	/// Shows who last updated the record on behalf of another user.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
		}
	}
	
	/// <summary>
	/// Enter the user or team who is assigned to manage the record. This field is updated every time the record is assigned to a different user.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	public Microsoft.Xrm.Sdk.EntityReference OwnerId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
		}
		set
		{
			this.OnPropertyChanging("OwnerId");
			this.SetAttributeValue("ownerid", value);
			this.OnPropertyChanged("OwnerId");
		}
	}
	
	/// <summary>
	/// Unique identifier of the business unit that owns the untracked email activity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
		}
	}
	
	/// <summary>
	/// Unique identifier of the team who owns the untracked email activity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
	public Microsoft.Xrm.Sdk.EntityReference OwningTeam
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
		}
	}
	
	/// <summary>
	/// Unique identifier of the user who owns the untracked email activity.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	public Microsoft.Xrm.Sdk.EntityReference OwningUser
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
		}
	}
	
	/// <summary>
	/// Choose the record that the untracked email relates to.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("regardingobjectid")]
	public Microsoft.Xrm.Sdk.EntityReference RegardingObjectId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("regardingobjectid");
		}
		set
		{
			this.OnPropertyChanging("RegardingObjectId");
			this.SetAttributeValue("regardingobjectid", value);
			this.OnPropertyChanged("RegardingObjectId");
		}
	}
	
	/// <summary>
	/// Type a short description about the objective or primary topic of the UntrackedEmail.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subject")]
	public string Subject
	{
		get
		{
			return this.GetAttributeValue<string>("subject");
		}
		set
		{
			this.OnPropertyChanging("Subject");
			this.SetAttributeValue("subject", value);
			this.OnPropertyChanged("Subject");
		}
	}
	
	/// <summary>
	/// Choose the local currency for the record to make sure budgets are reported in the correct currency.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
	public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
	{
		get
		{
			return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
		}
		set
		{
			this.OnPropertyChanging("TransactionCurrencyId");
			this.SetAttributeValue("transactioncurrencyid", value);
			this.OnPropertyChanged("TransactionCurrencyId");
		}
	}
	
	/// <summary>
	/// Version number of the untracked email message.
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
	public System.Nullable<long> VersionNumber
	{
		get
		{
			return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
		}
	}
	
	/// <summary>
	/// N:1 business_unit_untrackedemail_activities
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_untrackedemail_activities")]
	public BusinessUnit business_unit_untrackedemail_activities
	{
		get
		{
			return this.GetRelatedEntity<BusinessUnit>("business_unit_untrackedemail_activities", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_untrackedemail_createdby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_untrackedemail_createdby")]
	public SystemUser lk_untrackedemail_createdby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_untrackedemail_createdby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_untrackedemail_createdonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_untrackedemail_createdonbehalfby")]
	public SystemUser lk_untrackedemail_createdonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_untrackedemail_createdonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_untrackedemail_modifiedby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_untrackedemail_modifiedby")]
	public SystemUser lk_untrackedemail_modifiedby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_untrackedemail_modifiedby", null);
		}
	}
	
	/// <summary>
	/// N:1 lk_untrackedemail_modifiedonbehalfby
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_untrackedemail_modifiedonbehalfby")]
	public SystemUser lk_untrackedemail_modifiedonbehalfby
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("lk_untrackedemail_modifiedonbehalfby", null);
		}
	}
	
	/// <summary>
	/// N:1 owner_untrackedemails
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("owner_untrackedemails")]
	public Owner owner_untrackedemails
	{
		get
		{
			return this.GetRelatedEntity<Owner>("owner_untrackedemails", null);
		}
		set
		{
			this.OnPropertyChanging("owner_untrackedemails");
			this.SetRelatedEntity<Owner>("owner_untrackedemails", null, value);
			this.OnPropertyChanged("owner_untrackedemails");
		}
	}
	
	/// <summary>
	/// N:1 TransactionCurrency_UntrackedEmail
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_UntrackedEmail")]
	public TransactionCurrency TransactionCurrency_UntrackedEmail
	{
		get
		{
			return this.GetRelatedEntity<TransactionCurrency>("TransactionCurrency_UntrackedEmail", null);
		}
		set
		{
			this.OnPropertyChanging("TransactionCurrency_UntrackedEmail");
			this.SetRelatedEntity<TransactionCurrency>("TransactionCurrency_UntrackedEmail", null, value);
			this.OnPropertyChanged("TransactionCurrency_UntrackedEmail");
		}
	}
	
	/// <summary>
	/// N:1 user_untrackedemail
	/// </summary>
	[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
	[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_untrackedemail")]
	public SystemUser user_untrackedemail
	{
		get
		{
			return this.GetRelatedEntity<SystemUser>("user_untrackedemail", null);
		}
	}
}
#pragma warning restore CS1591
